###############################################################################
# CUIDADO!
# Esta script é gerenciado pelo CI. Não altere ou mude sem saber o que está
# fazendo.
###############################################################################
# CI-STEP: Destruir e (re)criar container de versão de staging
#
# - o container usa o banco de dados cgsy-postgres criado externamente, que é o
#   mesmo utilizado para o ambiente de desenvolvimento (local).
# - IMPORTANTE manter o nome do container como "manage-staging" pois outros
#   scripts utilizam esta referência.
# - env-file "env-manage-staging" é construído pelo CI dinamicamente por causa
#   das informações sensíveis.
###############################################################################
version: '3'
services:
  # Preparação de volumes.
  migration:
    image: cgsy-staging
    container_name: migration-staging
    entrypoint:
      - /services/migration/container-entry.sh
    env_file: /tmp/staging-files/env-manage-staging
    networks:
      - postgres

  volume:
    image: cgsy-staging
    container_name: volume-staging
    depends_on:
      - migration
    entrypoint:
      - /services/volume/container-entry.sh
    env_file: /tmp/staging-files/env-manage-staging
    volumes:
      - /etc/localtime:/etc/localtime
      - /media:/var/www/cgsy/media

  cron:
    image: cgsy-staging
    container_name: cron-staging
    depends_on:
      - migration
      - volume
    entrypoint:
      - /services/cron/container-entry.sh
    networks:
      - postgres
      - mailhog
    env_file: /tmp/staging-files/env-manage-staging
    volumes:
      - /etc/localtime:/etc/localtime
      - /media:/var/www/cgsy/media

  manage:
    image: cgsy-staging
    container_name: manage-staging
    depends_on:
      - migration
    entrypoint:
      - /services/web/manage/container-entry.sh
    networks:
      - postgres
      - mailhog
      - wkhtmltopdf
    ports:
      - "8080:80"
    env_file: /tmp/staging-files/env-manage-staging
    volumes:
      - /etc/localtime:/etc/localtime
      - /media:/var/www/cgsy/media

networks:
  postgres:
    external:
      name: env_postgres
  mailhog:
    external:
      name: env_mailhog
  wkhtmltopdf:
    external:
      name: env_wkhtmltopdf
