# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0010_auto_20180602_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('subscription', 'Inscrição'), ('service', 'Atividade Extra'), ('product', 'Opcional')], default='subscription', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('debt', 'pendente'), ('paid', 'pago'), ('credit', 'com crédito')], default='debt', help_text='qual a situação atual da pendência', max_length=20, null=True, verbose_name='status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='valor cobrado ao comprador', max_digits=11, null=True, verbose_name='valor')),
                ('liquid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='valor que o organizador irá receber', max_digits=11, null=True, verbose_name='valor líquido')),
                ('installments', models.PositiveIntegerField(default=1, help_text='número de parcelas da compra', verbose_name='número de parcelas')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='valor da parcela')),
                ('installment_interests_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='valor dos juros do parcelamento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'pendência',
                'verbose_name_plural': 'pendências',
            },
        ),
        migrations.CreateModel(
            name='DebtConfig',
            fields=[
                ('transfer_tax', models.BooleanField(help_text='se taxa foi transferida ao participante', verbose_name='transferir taxa')),
                ('total_installments', models.PositiveIntegerField(default=1, help_text='total possível para parcelamento', verbose_name='total de parcelas')),
                ('free_installments', models.PositiveIntegerField(default=1, help_text='número de parcelas em que o organizador absorveu os juros', verbose_name='parcelas livre de juros')),
                ('interests_rate', models.DecimalField(decimal_places=3, max_digits=11, verbose_name='percentual de taxa de juros de parcelamento')),
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='payment_debt.Debt', verbose_name='pendência')),
            ],
            options={
                'verbose_name': 'configuração de pendência',
                'verbose_name_plural': 'configurações de pendências',
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='gatheros_subscription.Subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together=set([('type', 'subscription')]),
        ),
    ]
