# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='item_id',
            field=models.CharField(default='unknown_id', max_length=255, verbose_name='id do item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='name',
            field=models.CharField(default='unknown_name', max_length=255, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
