# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_debt', '0002_auto_20180604_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together=set([]),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['type', 'item_id'], name='payment_deb_type_cdc845_idx'),
        ),
    ]
