# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 20:15
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0004_auto_20180307_1437'),
        ('gatheros_event', '0010_event_congressy_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='affiliate', serialize=False, to='gatheros_event.Person', verbose_name='pessoa')),
                ('status', models.CharField(blank=True, choices=[('suspended', 'Suspenso'), ('active', 'Ativo')], default='active', max_length=30, null=True, verbose_name='status')),
                ('bank_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate', to='payment.BankAccount', verbose_name='conta bancária')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
            bases=(base.models.EntityMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, help_text='Percentual de participação da afiliação.', max_digits=5, verbose_name='percentual')),
                ('link_whatsapp', models.TextField(verbose_name='link WhatsApp')),
                ('link_facebook', models.TextField(verbose_name='link Facebok')),
                ('link_twitter', models.TextField(verbose_name='link Twitter')),
                ('link_direct', models.TextField(verbose_name='link Direto')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='affiliate.Affiliate', verbose_name='afiliado')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='gatheros_event.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'Afiliação',
                'verbose_name_plural': 'Afiliações',
            },
            bases=(base.models.EntityMixin, models.Model),
        ),
    ]
