clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  build-version:
    image: indiehosters/git
    pull: true
    commands:
      - ./bin/version.sh > version

  build-staging:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - |
        echo "Building version: `cat ./version`"
      - |
        docker build \
          -t cgsy-staging:`cat ./version` \
          -f ./conf/staging/Dockerfile .
