# Branches added globally
branches:
  include: [master, release/*, hotfix/*]

# Custom definition for cloning, adding tags and depth
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

# Steps of deploy, according to configurations and conditionals
pipeline:
  create-db-prod-backup:
    image: postgres:9.6-alpine
    volumes:
      - /tmp/bkp:/tmp/bkp
    commands:
      - ./bin/env/staging/backup-prod-db.sh
    when:
      branch: [ hotfix/*, release/* ]

  recreate-staging-db:
    image: tmaier/docker-compose
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh ./bin/env/staging/start-postgres.sh
    when:
      branch:
        include: [ hotfix/*, release/* ]

  save-staging-version:
    image: alpine
    pull: true
    commands:
      - basename ${DRONE_COMMIT_BRANCH} > version
      - echo "${DRONE_BUILD_NUMBER}" > build_number
      - echo "${DRONE_COMMIT_AUTHOR}" > build_author
      - echo "${DRONE_BUILD_LINK}" > build_link
    when:
      branch: [ hotfix/*, release/* ]

  build-staging-image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - |
        printf "Building version: `cat ./version` - build `cat ./build_number`"
        printf " , por `cat ./build_author`\n\n"
      - |
        docker build \
          -t cgsy-staging \
          -f ./conf/staging/Dockerfile .
    when:
      branch: [ hotfix/*, release/* ]

  deploy-staging-env:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "AWS_KEY=$${AWS_KEY}"
      - echo "AWS_SECRET=$${AWS_SECRET}"
      - echo "DOMAIN=$${DOMAIN_STAGING}"
      - echo "DOMAIN=${DOMAIN_STAGING}"
      - echo "FORCE_HTTPS=${FORCE_HTTPS_STAGING}"
      - echo "BUCKET_LOCATION=${BUCKET_LOCATION}"
      - echo "BUCKET_NAME=${BUCKET_NAME}"
      - echo "CRON_SYNC_MINUTES_OUT=${CRON_SYNC_MINUTES_OUT}"
      - echo "CRON_SYNC_MINUTES_IN=${CRON_SYNC_MINUTES_IN}"
      - echo "DBHOST=${DBHOST_STAGING}"
      - echo "DBUSER=${DBUSER_STAGING}"
      - echo "DBNAME=${DBNAME_STAGING}"
      - echo "DBPORT=${DBPORT_STAGING}"
      #- sh ./bin/env/staging/start-cgsy-staging.sh

    when:
      branch: [ hotfix/*, release/* ]

  notify-staging-on-telegram:
    image: appleboy/drone-telegram
    pull: true
    token: 482555800:AAHSWjlo_kufu069-5N_ecp9ZqQ_r1zpep8
#    to: -275808686 # ID chat Congressy
    to: 245012348 # ID hugoseabra
    format: markdown
    message: >
      *{{uppercase build.status }} - Ambiente RC*


      *Repo:* {{ repo.name }} das {{datetime build.started "3:04PM" "UTC"}} às {{datetime build.finished"3:04PM" "UTC"}}

      *Branch:* {{ commit.branch }}

      *Build:* {{build.number}}

      *Duração:* {{duration build.started build.finished}}

      *Autor:* {{ commit.author }}

      *Mensagem:*

      ```
      {{ commit.message }}
      ```


      *Ambiente:* https://test.congressy.com/login/


      *Build Link:* {{ build.link }}


      *Commit:* {{ commit.link }}


    when:
      status: [ success, failure ]
      branch: [ hotfix/*, release/* ]
