services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=cgsyplatform
      - POSTGRES_USER=congressy
      - POSTGRES_PASSWORD=congressy

volumes:
  postgres_backup:

pipeline:
  database-backup:
    image: postgres:9.6-alpine
    volumes:
      - postgres_backup:/bkp
    commands:
      - |
        PGPASSWORD=4UnADjyMjeeB7GSc pg_dump \
          --format=c \
          --host congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com \
          --port 5499 \
          --username congressy \
          cgsyplatform > /bkp/backup.sql
      - echo Backup size: `du -h /bkp/backup.sql`

  database-ping:
    image: postgres:9.6-alpine
    pull: true
    commands:
      - sleep 10
      - |
        psql -U congressy -d cgsyplatform \
          -c "SELECT * FROM pg_catalog.pg_tables;"

  database-restore:
    image: postgres:9.6-alpine
    volumes:
      - postgres_backup:/bkp
    commands:
      - pg_restore -U congressy -n public -d cgsyplatform < /bkp/backup.sql
