clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  create-db-prod-backup:
    image: postgres:9.6-alpine
    volumes:
      - /tmp/bkp:/tmp/bkp
    commands:
      - mkdir -p /tmp/bkp/backup
      - |
        PGPASSWORD=4UnADjyMjeeB7GSc pg_dump \
          --host congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com \
          --port 5499 \
          --username congressy \
          --format=c \
          --verbose \
          cgsyplatform > /tmp/bkp/backup/backup.sql
      - |
        echo Backup size: `du -h /tmp/bkp/backup/backup.sql`
      - cp ./bin/dev/staging/db-restore.sh /tmp/bkp/.

    when:
      branch:
        include: [ hotfix/*, release/* ]

  recreate-staging-db:
    image: tmaier/docker-compose
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh /bin/dev/staging/start-postgres.sh
    when:
      branch:
        include: [ hotfix/*, release/* ]
