clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  save-prod-version:
    image: indiehosters/git
    pull: true
    commands:
      - ./bin/version.sh > version

    when:
      branch:
        include: [ master ]

  save-staging-version:
    image: indiehosters/git
    pull: true
    commands:
      - basename ${DRONE_COMMIT_BRANCH} > version

    when:
      branch:
        include: [ release/* ]

  build-staging:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - |
        echo "Building version: `cat ./version`"
      - |
        docker build \
          -t cgsy-staging:`cat ./version` \
          -f ./conf/staging/Dockerfile .

    when:
      branch:
        include: [ release/* ]
