clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  save-version:
    image: indiehosters/git
    pull: true
    commands:
      - ./bin/version.sh > version

  build-staging:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - basename `git rev-parse --abbrev-ref HEAD`

    when:
      branch:
        include: [ release/* ]
