pipeline:
  build:
    image: python:3.6-jessie
    pull: true
    commands:
      - python -c 'print("bla")' > /tmp/result.txt 2>&1
      - whoami >> /tmp/result.txt 2>&1
    when:
      branch: feature/deploy-drone.io

  ping:
    image: postgres:9.6-alpine
    pull: true
    commands:
      - sleep 10
      - |
        psql -U postgres -d test -h database \
          -c "SELECT * FROM pg_catalog.pg_tables;"

  telegram:
    image: appleboy/drone-telegram
    token: 482555800:AAHSWjlo_kufu069-5N_ecp9ZqQ_r1zpep8
    to: -275808686 # ID chat Congressy via https://api.telegram.org/<token>/getUpdates
    format: markdown
    message: > 
      {{build.status}}
      build {{build.number}}
      "{{commit.message}}"
      <{{build.link}}>
    document:
      - /tmp/result.txt
    when:
      status: [ success, failure ]

  services:
    database:
      image: postgres:9.6-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=test

#  publish:
#    image: plugins/docker
#    repo: octocat/hello-world
#    tags: [ latest, 1, 1.0, 1.0.0 ]

#  branches:
#    include: [ master, release/*, hotfix/* ]