clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  database-backup:
    image: postgres:9.6-alpine
    volumes:
      - /tmp/bkp:/tmp/bkp
    commands:
      - |
        PGPASSWORD=4UnADjyMjeeB7GSc pg_dump \
          --format=c \
          --host congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com \
          --port 5499 \
          --username congressy \
          --verbose \
          cgsyplatform > /tmp/bkp/backup.sql
      - |
        echo Backup size: `du -h /bkp/backup.sql`

    when:
      branch:
        include: [ hotfix/*, release/* ]
