pipeline:
  build:
    image: python:3.6-jessie
    pull: true
    commands:
      - python -c 'print("bla")' > /tmp/result.txt 2>&1
      - whoami >> /tmp/result.txt 2>&1
    when:
      branch: feature/deploy-drone.io
