# Branches added globally
branches:
  include: [master, release/*, hotfix/*]

# Custom definition for cloning, adding tags and depth
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

# Steps of deploy, according to configurations and conditionals
pipeline:
  deploy-staging-env:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: AWS_KEY
        target: AWS_KEY
      - source: AWS_SECRET
        target: AWS_SECRET
      - source: DOMAIN_STAGING
        target: DOMAIN
      - source: FORCE_HTTPS_STAGING
        target: FORCE_HTTPS
    commands:
      - echo "AWS_KEY=${AWS_KEY}"
      - echo "AWS_SECRET=${AWS_SECRET}"
      - echo "DOMAIN=${DOMAIN}"
      - echo "FORCE_HTTPS=${FORCE_HTTPS}"
      - echo "BUCKET_LOCATION=${BUCKET_LOCATION}"
      - echo "BUCKET_NAME=${BUCKET_NAME}"
      - echo "CRON_SYNC_MINUTES_OUT=${CRON_SYNC_MINUTES_OUT}"
      - echo "CRON_SYNC_MINUTES_IN=${CRON_SYNC_MINUTES_IN}"
      - echo "DBHOST=${DBHOST_STAGING}"
      - echo "DBUSER=${DBUSER_STAGING}"
      - echo "DBNAME=${DBNAME_STAGING}"
      - echo "DBPORT=${DBPORT_STAGING}"
      #- sh ./bin/env/staging/start-cgsy-staging.sh

    when:
      branch: [ hotfix/*, release/* ]
