services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=congressy
      - POSTGRES_DB=congressy
      - POSTGRES_PASSWORD=congressy

pipeline:
  database-backup:
    image: postgres:9.6-alpine
    pull: true
    volumes:
      - postgres_backup:/bkp
    commands:
      - sleep 10
      - |
        PGPASSWORD=4UnADjyMjeeB7GSc pg_dump \
          --format=c \
          --host congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com \
          --port 5499 \
          --username congressy \
          cgsyplatform > /bkp/backup.sql

  database-restore:
    image: postgres:9.6-alpine
    pull: true
    volumes:
      - postgres_backup:/bkp
    commands:
      - sleep 10
      - pg_restore -U postgres -n public -d cgsyplatform < /bkp/backup.sql

