# Branches added globally
branches:
  include: [develop, master, release/*, hotfix/*]

# Custom definition for cloning, adding tags and depth
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

# Steps of deploy, according to configurations and conditionals
pipeline:
  create-db-prod-backup:
    image: postgres:9.6-alpine
    volumes:
      - /tmp/bkp:/tmp/bkp
    commands:
      - mkdir -p /tmp/bkp/backup
      - |
        PGPASSWORD=4UnADjyMjeeB7GSc pg_dump \
          --host congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com \
          --port 5499 \
          --username congressy \
          --format=c \
          --verbose \
          cgsyplatform > /tmp/bkp/backup/backup.sql
      - |
        echo Backup size: `du -h /tmp/bkp/backup/backup.sql`
      - cp ./bin/dev/staging/db-restore.sh /tmp/bkp/.

    when:
      branch: [ hotfix/*, release/* ]

  recreate-staging-db:
    image: tmaier/docker-compose
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh ./bin/dev/staging/start-postgres.sh
    when:
      branch:
        include: [ hotfix/*, release/* ]

  save-staging-version:
    image: indiehosters/git
    pull: true
    commands:
      - basename ${DRONE_COMMIT_BRANCH} > version
    when:
      branch: [ hotfix/*, release/* ]

  build-staging-image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - |
        echo "Building version: `cat ./version`"
      - |
        docker build \
          -t cgsy-staging \
          -f ./conf/staging/Dockerfile .
    when:
      branch: [ hotfix/*, release/* ]

  deploy-staging-env:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh ./bin/dev/staging/start-cgsy-staging.sh
    when:
      branch: [ hotfix/*, release/* ]

  notify-staging-on-telegram:
    image: appleboy/drone-telegram
    pull: true
    token: 482555800:AAHSWjlo_kufu069-5N_ecp9ZqQ_r1zpep8
#    to: -275808686 # ID chat Congressy
    to: 245012348 # ID hugoseabra
    format: markdown
    message: >
      *{{uppercase build.status }} - Ambiente RC*

      *Repo:* {{ repo.name }} das {{datetime build.started "3:04PM" "UTC"}} às {{datetime build.finished"3:04PM" "UTC"}}

      *Branch:* {{ commit.branch }}

      *Build:* {{build.number}}

      *Duração:* {{duration build.started build.finished}}

      *Autor:* {{ commit.author }}

      *Mensagem:*
      ```
      {{ commit.message }}
      ```
      -- ---

      *Ambiente:* https://test.congressy.com/login/

      *Build Link:* {{ build.link }}

      *Commit:* {{ commit.link }}


    when:
      status: [ success, failure ]
      branch: [ develop, hotfix/*, release/* ]
