# Branches added globally
branches:
  include: [master, release/*, hotfix/*]

# Custom definition for cloning, adding tags and depth
clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

# Steps of deploy, according to configurations and conditionals
pipeline:
  save-prod-version:
    image: indiehosters/git
    pull: true
    commands:
#      - git describe --abbrev=0 > ./version
      - git tag -l
      - echo ${DRONE_TAG}
    when:
      status: [ success, failure ]
      branch: [ hotfix/*, release/* ]

#  build-prod-images:
#    image: docker
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    commands:
#      - |
#        echo "Building latest version: `cat ./version`"
#      - |
#        docker build --rm \
#          -t 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest \
#          -f ./conf/deploy/Dockerfile .
#      - |
#        echo "Building tagged version: `cat ./version`"
#      - |
#        docker build --rm \
#          -t 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:`cat ./version` \
#          -f ./conf/deploy/Dockerfile .
