pipeline:
  build-staging:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - export IMAGE_TAG=`./bin/version.sh`
      - |
        docker build \
          -t cgsy-staging:${IMAGE_TAG} \
          -f ./conf/staging/Dockerfile .
