pipeline:
  build-staging:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - |
        docker build \
          -t cgsy-staging \
          -f ./conf/staging/Dockerfile .
