# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 15:01
from __future__ import unicode_literals

import base.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0016_auto_20180924_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('liquid_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='total líquido a pagar')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='total a pagar')),
                ('num_installments', models.PositiveIntegerField(verbose_name='número de parcelas')),
                ('expiration_day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='vencimento todo dia')),
                ('limit_date', models.DateField(verbose_name='data limite de parcelamento')),
                ('minimum_amount_creation', models.DateField(editable=False, verbose_name='montante mínimo para parcelamento')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='valor mínimo de parcelamento')),
                ('minimum_installment_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='valor mínimo de parcela')),
                ('status', models.CharField(choices=[('open', 'aberto'), ('cancelled', 'cancelado'), ('fully_paid', 'quitado')], default='open', max_length=20, verbose_name='status')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_contracts', to='gatheros_subscription.Subscription', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'Contrato de Parcelamento',
                'verbose_name_plural': 'Contratos de Parcelamento',
            },
            bases=(base.models.EntityMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InstallmentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='valor')),
                ('expiration_day', models.PositiveIntegerField(verbose_name='vencimento')),
                ('installment_number', models.PositiveIntegerField(verbose_name='número da parcela')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_parts', to='installment.InstallmentContract', verbose_name='parcela de inscrição')),
            ],
            options={
                'verbose_name': 'Parcela de Contrato',
                'verbose_name_plural': 'Parcelas de Contrato',
            },
            bases=(base.models.EntityMixin, models.Model),
        ),
    ]
