# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='liquid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='total líquido a pagar'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='valor mínimo por parcela'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='minimum_amount_creation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='valor mínimo para habilitar parcelamento'),
        ),
    ]
