# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_transaction', to='payment.Transaction', verbose_name='transação da parcela'),
        ),
    ]
