# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 10:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0002_auto_20180119_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gatheros_subscription.Subscription')),
            ],
        ),
    ]
