# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0002_auto_20180119_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('processing', 'Processando'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('waiting_payment', 'Aguardando pagamento'), ('refunded', 'Estornado'), ('pending_refund', 'Aguardando estorno'), ('refused', 'Recusada'), ('chargedback', 'Chargeback')], max_length=30, null=True)),
                ('type', models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('credit_card', 'Cartão de credito')], max_length=30, null=True)),
                ('date_created', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='gatheros_subscription.Subscription')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('processing', 'Processando'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('waiting_payment', 'Aguardando pagamento'), ('refunded', 'Estornado'), ('pending_refund', 'Aguardando estorno'), ('refused', 'Recusada'), ('chargedback', 'Chargeback')], max_length=30, null=True)),
                ('date_created', models.CharField(blank=True, max_length=30, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='payment.Transaction')),
            ],
            options={
                'verbose_name': 'Status de Transação',
                'verbose_name_plural': 'Status de Transações',
            },
        ),
    ]
