# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 20:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Transaction')),
            ],
        ),
    ]
