# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactionstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'verbose_name': 'Status de Transação', 'verbose_name_plural': 'Status de Transações'},
        ),
    ]
