# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 15:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20180307_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'ordering': ['date_created'], 'verbose_name': 'Status de Transação', 'verbose_name_plural': 'Status de Transações'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'), ('033', 'Santander'), ('104', 'Caixa Economica'), ('756', 'BANCOOB - Banco Cooperativo do Brasil'), ('756', 'Sicoob')], max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Banco'),
        ),
    ]
