# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_liquid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='boleto_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento do boleto'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='boleto_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL do boleto'),
        ),
    ]
