# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20180427_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='subscription_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='liquid_amount',
            new_name='subscription_liquid_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='optional_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='optional_liquid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
