# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20180516_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='optional_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='optional_liquid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='valor líquido do organizador'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='liquid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
