# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0010_auto_20180602_0056'),
        ('payment', '0006_auto_20180516_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('boleto', 'Boleto'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('paycheck', 'Cheque'), ('bank_deposit', 'Depósito'), ('money', 'Dinheiro'), ('bank_transfer', 'Transferência Bancária'), ('waiting_payment', 'Aguardando Pagamento')], max_length=30)),
                ('manual', models.BooleanField(default=False, verbose_name='lançamento manual')),
                ('manual_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='author do lançamento manual')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='valor cobrado ao comprador', max_digits=11, null=True, verbose_name='valor')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('lot', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gatheros_subscription.Lot')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gatheros_subscription.Subscription')),
                ('transaction', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.Transaction')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
        ),
    ]
