# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_debt', '0001_initial'),
        ('payment', '0006_auto_20180516_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_type', models.CharField(choices=[('pagarme', 'Pagar.me')], default='pagarme', max_length=10)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider', serialize=False, to='payment_debt.Payment', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'provedor de transação',
                'verbose_name_plural': 'provedores de transação',
            },
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_card_first_digits',
            new_name='card_first_digits',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_card_holder',
            new_name='card_holder',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='credit_card_last_digits',
            new_name='card_last_digits',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='liquid_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lot_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='manual_author',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='manual_payment_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('credit_card', 'Cartão de credito')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payment.Provider', verbose_name='provedor'),
        ),
    ]
