# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20180604_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_part',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='número de parcelas'),
        ),
    ]
