# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '__first__'),
        ('payment', '0009_transaction_installment_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='installment.Part', verbose_name='transação da parcela'),
        ),
    ]
