# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20190724_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payable',
            name='next_check',
        ),
        migrations.AddField(
            model_name='payable',
            name='synced',
            field=models.BooleanField(default=False, editable=False, verbose_name='sincronizado com provedor'),
        ),
        migrations.AddField(
            model_name='splitrule',
            name='checkable',
            field=models.BooleanField(default=True, editable=False, verbose_name='regra passível de sincronização'),
        ),
        migrations.AddField(
            model_name='splitrule',
            name='next_check',
            field=models.DateTimeField(editable=False, null=True, verbose_name='última checagem'),
        ),
    ]
