# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200125_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='card_holder_name',
            field=models.CharField(blank=True, help_text='Nome impresso no último cartão utilizado.', max_length=150, null=True, verbose_name='Nome impresso no cartão'),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='referência'),
        ),
    ]
