# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200125_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='referência'),
        ),
    ]
