version: "3"
services:
  redis:
    image: redis:4-alpine
    restart: always
    networks:
      - redis
    volumes:
      - "redis:/data"

  # Preparação de volumes.
  volume:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    entrypoint:
      - /services/volume/container-entry.sh
    volumes:
      - "./media:/var/www/cgsy/media"
    env_file: ./env-file

  cron:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    depends_on:
      - volume
    entrypoint:
      - /services/cron/container-entry.sh
    volumes:
      - "./media:/var/www/cgsy/media"
    env_file: ./env-file

  manage:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    depends_on:
      - volume
    networks:
      - redis
    ports:
      - "8000:80"
    entrypoint:
      - /services/web/manage/container-entry.sh
    volumes:
      - "./media:/var/www/cgsy/media"
    env_file: ./env-file

networks:
  redis:

volumes:
  redis:
