version: "3.5"
services:
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    networks:
      - wkhtmltopdf
    volumes:
      - /etc/localtime:/etc/localtime

  celery:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-celery
    networks:
      - wkhtmltopdf
    entrypoint:
      - /deploy/services/celery/container-entry.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    env_file: ./env-file

  manage:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-manage
    healthcheck:
      test: "/code/bin/env/healthcheck.sh"
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
    ports:
      - "8000:8000"
    entrypoint:
      - /deploy/services/web/manage/container-entry.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    env_file:
      - ./env-file
      - ./env-manage-file

  partner:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-partner
    healthcheck:
      test: "/code/bin/env/healthcheck.sh"
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
    ports:
      - "8001:8000"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    entrypoint:
      - /deploy/services/web/partner/container-entry.sh
    env_file:
      - ./env-file
      - ./env-partner-file

  admin_intranet:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-admin
    healthcheck:
      test: "/code/bin/env/healthcheck.sh"
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
    ports:
      - "8002:80"
    entrypoint:
      - /deploy/services/web/admin_intranet/container-entry.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    env_file:
      - ./env-file
      - ./env-admin_intranet-file

networks:
  wkhtmltopdf:
