version: "3"
services:
  # Preparação de volumes.
  cron:
    image: cgsy:latest
    entrypoint:
      - /services/cron/container-entry.sh
    volumes:
      - "./media:/var/www/cgsy/media"
    env_file: env-file
