version: "3.5"
services:
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    networks:
      - wkhtmltopdf

  manage:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-manage
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
    ports:
      - "8000:80"
    entrypoint:
      - /services/web/manage/container-entry.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/var/www/cgsy/media
      - ./shared-volume/exporter:/tmp/exporter
    env_file:
      - ./env-file
      - ./env-manage-file

  partner:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: HOSTNAME-partner
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
    ports:
      - "8001:80"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./shared-volume/media:/var/www/cgsy/media
      - ./shared-volume/exporter:/tmp/exporter
    entrypoint:
      - /services/web/partner/container-entry.sh
    env_file:
      - ./env-file
      - ./env-partner-file

#  admin_intranet:
#    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
#    restart: unless-stopped
#    hostname: HOSTNAME-admin
#    depends_on:
#      - wkhtmltopdf
#    networks:
#      - wkhtmltopdf
#    ports:
#      - "8002:80"
#    entrypoint:
#      - /services/web/admin_intranet/container-entry.sh
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./shared-volume/media:/var/www/cgsy/media
#      - ./exporter:/tmp/exporter
#    env_file:
#      - ./env-file
#      - ./env-admin_intranet-file

networks:
  wkhtmltopdf:
