version: "3"
services:
  # Preparação de volumes.
  volume:
    image: cgsy:latest
    entrypoint:
      - /services/volume/container-entry.sh
    volumes:
      - "./media:/var/www/cgsy/media"
    env_file: /tmp/env-file

networks:
  redis:

volumes:
  redis:
