version: "3.5"
services:
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    networks:
      - wkhtmltopdf

  celery:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: server5-celery
    networks:
      - wkhtmltopdf
    entrypoint:
      - /deploy/services/celery/container-entry.sh
    volumes:
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    env_file: ./env-file

  manage:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: server5-manage
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
      - reverse_proxy_net
    ports:
      - "8000"
    entrypoint:
      - /deploy/services/web/manage/container-entry.sh
    volumes:
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    env_file:
      - ./env-file
      - ./env-manage-file
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.weight=10"
      - "traefik.backend=cgsy-manage"
      - "traefik.protocol=http"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:ev.congressy.com;PathPrefix:/manage,/admin,/remarketing,/account,/invitations,/pagarme,/captcha,/hotsite,/api,/static-manage,/media-manage,/ckeditor"
      - "traefik.docker.network=reverse_proxy_net"
      - "traefik.frontend.entryPoints=http"

  partner:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    restart: unless-stopped
    hostname: server5-partner
    depends_on:
      - wkhtmltopdf
    networks:
      - wkhtmltopdf
      - reverse_proxy_net
    ports:
      - "8000"
    volumes:
      - ./shared-volume/media:/code/media
      - ./shared-volume/exporter:/tmp/exporter
      - ./shared-volume/qrcodes:/tmp/qrcodes
      - ./shared-volume/barcodes:/tmp/barcodes
      - ./shared-volume/vouchers:/tmp/vouchers
    entrypoint:
      - /deploy/services/web/partner/container-entry.sh
    env_file:
      - ./env-file
      - ./env-partner-file
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.weight=10"
      - "traefik.backend=cgsy-partner"
      - "traefik.protocol=http"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:parceiros.congressy.com"
      - "traefik.docker.network=reverse_proxy_net"
      - "traefik.frontend.entryPoints=http"

networks:
  wkhtmltopdf:
  reverse_proxy_net:
    external: true

