[accessLog]
  filePath = "/dev/stdout"
[traefikLog]
   filePath = "/dev/stdout"

[entryPoints]
  [entryPoints.http]
  address = ":80"
     [entryPoints.http.redirect]
     regex = "^http://(.*)$"
     replacement = "https://$1"
