# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 15:04
from __future__ import unicode_literals

import csv_importer.models.csv_import_file
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_event', '0021_event_allow_importing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('csv_file', models.FileField(upload_to=csv_importer.models.csv_import_file.get_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_file', to='gatheros_event.Event', verbose_name='evento')),
            ],
        ),
    ]
