# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:01
from __future__ import unicode_literals

import csv_importer.models.csv_file_config
import csv_importer.models.storage
import csv_importer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfileconfig',
            name='success_csv_file',
        ),
        migrations.AlterField(
            model_name='csvfileconfig',
            name='error_csv_file',
            field=models.FileField(storage=csv_importer.models.storage.OverwriteStorage(), upload_to=csv_importer.models.csv_file_config.get_err_file_path, validators=[csv_importer.validators.validate_csv_only_file]),
        ),
    ]
