# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0013_auto_20180709_1356'),
        ('csv_importer', '0002_csvimportfile_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportfile',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csv_file', to='gatheros_subscription.Lot', verbose_name='lot'),
            preserve_default=False,
        ),
    ]
