# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='google_maps_img',
        ),
        migrations.RemoveField(
            model_name='place',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='place',
            name='google_streetview_img',
        ),
        migrations.RemoveField(
            model_name='place',
            name='google_streetview_link',
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanu_locations.City', verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='sexo'),
        ),
    ]
