# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 02:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

from core.model import validator


class Migration(migrations.Migration):
    dependencies = [
        ('gatheros_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='account',
            field=models.CharField(blank=True, max_length=13, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_type',
            field=models.CharField(blank=True,
                                   choices=[('conta_corrente', 'Conta corrente'), ('conta_poupanca', 'Conta poupanca'),
                                            ('conta_corrente_conjunta', 'Conta corrente conjunta'),
                                            ('conta_poupanca_conjunta', 'Conta poupanca conjunta')],
                                   default='conta_corrente', max_length=25, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='organization',
            name='active_bank_account',
            field=models.BooleanField(default=False, verbose_name='desativo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='agency',
            field=models.CharField(blank=True, max_length=5, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_code',
            field=models.CharField(blank=True,
                                   choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'),
                                            ('033', 'Santander'), ('104', 'Caixa Economica')], max_length=3, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='cnpj_ou_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='kanu_locations.City', verbose_name='cidade-UF'),
        ),

        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (
                ('can_invite', 'Can invite members'), ('can_view', 'Can view'), ('can_add_event', 'Can add event'),
                ('can_view_members', 'Can view members'), ('can_manage_members', 'Can manage members'),
                ('can_manage_places', 'Can manage places'), ('can_manage_fields', 'Can manage form fields')),
                     'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='account',
            field=models.CharField(blank=True, max_length=13, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')],
                                   verbose_name='Numero da Conta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')],
                                   verbose_name='Dígito verificador da agência'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='agency',
            field=models.CharField(blank=True, max_length=5, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')],
                                   verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_code',
            field=models.CharField(blank=True,
                                   choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'),
                                            ('033', 'Santander'), ('104', 'Caixa Economica')], max_length=3, null=True,
                                   validators=[django.core.validators.RegexValidator('^\\d{1,10}$')],
                                   verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Dígito verificador da Conta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome completo ou razão social'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscription_type',
            field=models.CharField(choices=[('disabled', 'Desativadas'),
                                            ('simple', 'Simples (gratuitas)'),
                                            (
                                                'by_lots',
                                                'Gerenciar por lotes')],
                                   default='simple',
                                   help_text='Como gostaria de gerenciar as inscrições de seu evento?',
                                   max_length=15, verbose_name='inscrições'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='data de nasc.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True,
                                    verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'),
                                                        ('F', 'Feminino')],
                                   default='M', max_length=1, null=True,
                                   verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True,
                                   validators=[validator.phone_validator],
                                   verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True,
                                   help_text='Rua / Avenida / Viela / etc.',
                                   max_length=255, null=True,
                                   verbose_name='logradouro'),
        ),
    ]
