# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 02:23
from __future__ import unicode_literals

from django.db import migrations, models

from core.model import validator


class Migration(migrations.Migration):
    dependencies = [
        ('gatheros_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscription_type',
            field=models.CharField(choices=[('disabled', 'Desativadas'),
                                            ('simple', 'Simples (gratuitas)'),
                                            (
                                                'by_lots',
                                                'Gerenciar por lotes')],
                                   default='simple',
                                   help_text='Como gostaria de gerenciar as inscrições de seu evento?',
                                   max_length=15, verbose_name='inscrições'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='data de nasc.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True,
                                    verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'),
                                                        ('F', 'Feminino')],
                                   default='M', max_length=1, null=True,
                                   verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True,
                                   validators=[validator.phone_validator],
                                   verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True,
                                   help_text='Rua / Avenida / Viela / etc.',
                                   max_length=255, null=True,
                                   verbose_name='logradouro'),
        ),
    ]
