# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, help_text='Rua / Avenida / Viela / etc.', max_length=255, null=True, verbose_name='logradouro'),
        ),
    ]
