# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 16:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0002_auto_20180119_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='cpf',
        ),
        migrations.AddField(
            model_name='organization',
            name='active_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='charge_transfer_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_created',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='document_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='recipient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active_bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cnpj_ou_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ da conta com ou sem pontuações'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Dígito verificador da Conta'),
        ),
    ]
