# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0002_auto_20171227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscription_type',
            field=models.CharField(choices=[('disabled', 'Desativadas'), ('simple', 'Simples (gratuitas)')], default='simple', help_text='Como gostaria de gerenciar as inscrições de seu evento?', max_length=15, verbose_name='inscrições'),
        ),
    ]
