# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import gatheros_event.models.info
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0002_auto_20171227_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='lead',
            field=models.CharField(blank=True, help_text='Inspire aos visitantes a permanecerem no website do seu evento', max_length=255, null=True, verbose_name='descrição rápida'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscription_type',
            field=models.CharField(choices=[('disabled', 'Desativadas'), ('simple', 'Simples (gratuitas)')], default='simple', help_text='Como gostaria de gerenciar as inscrições de seu evento?', max_length=15, verbose_name='inscrições'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_html',
            field=models.TextField(help_text='Descreva sobre o que se trata o seu evento', verbose_name='descrição (HTML)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_main',
            field=stdimage.models.StdImageField(blank=True, help_text='Imagem única da descrição do evento: 480px x 638px', null=True, upload_to=gatheros_event.models.info.get_image_path, validators=[stdimage.validators.MinSizeValidator(480, 638), stdimage.validators.MaxSizeValidator(1400, 1861)], verbose_name='imagem principal'),
        ),
    ]
