# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0002_auto_20180119_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='account',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_type',
            field=models.CharField(blank=True, choices=[('conta_corrente', 'Conta corrente'), ('conta_poupanca', 'Conta poupanca'), ('conta_corrente_conjunta', 'Conta corrente conjunta'), ('conta_poupanca_conjunta', 'Conta poupanca conjunta')], default='conta_corrente', max_length=25, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='organization',
            name='active_bank_account',
            field=models.BooleanField(default=False, verbose_name='desativo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='agency',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'), ('033', 'Santander'), ('104', 'Caixa Economica')], max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanu_locations.City', verbose_name='cidade-UF'),
        ),
    ]
