# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0003_auto_20180103_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
