# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0003_auto_20180124_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='celular'),
        ),
    ]
