# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0003_auto_20180122_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('can_invite', 'Can invite members'), ('can_view', 'Can view'), ('can_add_event', 'Can add event'), ('can_view_members', 'Can view members'), ('can_manage_members', 'Can manage members'), ('can_manage_places', 'Can manage places'), ('can_manage_fields', 'Can manage form fields')), 'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
    ]
