# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0004_event_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lead',
            field=models.CharField(blank=True, help_text='Inspire aos visitantes a permanecerem no website do seu evento', max_length=255, null=True, verbose_name='descrição rápida'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_html',
            field=models.CharField(help_text='Descreva sobre o que se trata o seu evento', max_length=3000, verbose_name='descrição (HTML)'),
        ),
    ]
