# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0004_auto_20180123_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cpf',
        ),
        migrations.AddField(
            model_name='organization',
            name='cnpj_ou_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF ou CNPJ da conta com ou sem pontuações'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='account',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Numero da Conta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Dígito verificador da agência'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='agency',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'), ('033', 'Santander'), ('104', 'Caixa Economica')], max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Dígito verificador da Conta'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome completo ou razão social'),
        ),
    ]
