# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0005_auto_20180105_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description_html',
            field=models.TextField(help_text='Descreva sobre o que se trata o seu evento', verbose_name='descrição (HTML)'),
        ),
    ]
