# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0005_auto_20180209_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo ou razão social'),
        ),
    ]
