# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 16:30
from __future__ import unicode_literals

from django.db import migrations
import gatheros_event.models.event
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0006_auto_20180105_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_main',
            field=stdimage.models.StdImageField(blank=True, help_text='Imagem única da descrição do evento: 480px x 638px', null=True, upload_to=gatheros_event.models.event.get_image_path, validators=[stdimage.validators.MinSizeValidator(480, 638), stdimage.validators.MaxSizeValidator(1400, 1400)], verbose_name='imagem principal'),
        ),
    ]
