# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0003_auto_20180105_1929'),
        ('gatheros_event', '0006_auto_20180105_1446'),
    ]

    operations = [
    ]
