# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gatheros_event', '0006_auto_20180216_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='institution_cnpj',
            field=models.CharField(
                blank=True,
                help_text='CNPJ da empresa com a qual você está vinculado(a)',
                max_length=14, null=True,
                verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.CharField(
                blank=True,
                help_text='Cargo ou função que você exerce profissionalmente.',
                max_length=255, null=True,
                verbose_name='Cargo/Função'),
        ),
    ]
