# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0007_merge_20180108_1036'),
        ('gatheros_event', '0007_event_image_main'),
    ]

    operations = [
    ]
