# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('gatheros_event', '0008_auto_20180306_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='gatheros_event.Event', verbose_name='evento')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='survey.Survey', verbose_name='formulario')),
            ],
        ),
    ]
