# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0008_auto_20180306_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='zoom',
            field=models.CharField(blank=True, default=18, max_length=4, null=True, verbose_name='zoom do mapa'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='long',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do local'),
        ),
        migrations.AlterField(
            model_name='place',
            name='show_location',
            field=models.BooleanField(default=False, help_text='Marque para mostrar a localização do evento no site.', verbose_name='ativar localização no site'),
        ),
    ]
