# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0009_remove_event_lead'),
        ('gatheros_event', '0008_merge_20180108_1108'),
    ]

    operations = [
    ]
