# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 15:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import gatheros_event.models.event
import gatheros_event.models.info
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0010_event_congressy_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_main',
            field=stdimage.models.StdImageField(blank=True, help_text="Imagem única da descrição do evento: 480px x 638px. <a  target='_blank'href='http://via.placeholder.com/480x638'>Exemplo</a>", null=True, upload_to=gatheros_event.models.event.get_image_path, validators=[stdimage.validators.MinSizeValidator(480, 638), stdimage.validators.MaxSizeValidator(1400, 1400)], verbose_name='imagem principal'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_html',
            field=models.TextField(help_text='Descreva as normas de seu evento, como a programação, regras, reembolsos, palestrantes, atrações', verbose_name='descrição do evento'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_main',
            field=stdimage.models.StdImageField(blank=True, help_text="Banner do evento, mínimo de: 480px largura x 640px altura.(png/jpg) <a  target='_blank'href='http://via.placeholder.com/480x638'>Exemplo</a>", null=True, upload_to=gatheros_event.models.info.get_image_path, validators=[stdimage.validators.MinSizeValidator(480, 638), stdimage.validators.MaxSizeValidator(1400, 1861)], verbose_name='imagem principal'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lead',
            field=models.CharField(blank=True, help_text='Inspire aos visitantes a permanecerem no website do seu evento', max_length=255, null=True, verbose_name='descrição breve'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('341', 'Itau'), ('237', 'Bradesco'), ('033', 'Santander'), ('104', 'Caixa Economica'), ('756', 'BANCOOB - Banco Cooperativo do Brasil'), ('756', 'Sicoob'), ('748', 'BANCO COOPERATIVO SICREDI S.A.')], max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Banco'),
        ),
    ]
