# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0010_event_congressy_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_type',
            field=models.CharField(choices=[('rsvp-disabled', 'Aberto'), ('rsvp-open', 'Convidados associados terão um lote especial.'), ('rsvp-restricted', 'Somente associados poderão se inscrever.')], default='rsvp-disabled', help_text='Se há associados vinculados à organização, o evento poderá exibir um lote especial para eles, com um valor especial.', max_length=20, verbose_name='Distribuição de Público'),
        ),
    ]
