# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0011_auto_20180427_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_internal_subscription',
            field=models.BooleanField(default=False, help_text='Se ativado, organizadores poderão inserir inscrição interna manualmente.', verbose_name='permitir inscrição interna'),
        ),
        migrations.AddField(
            model_name='event',
            name='boleto_limit_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Limite (em dias) para permissão de pagamento de boleto do evento.', verbose_name='Limite para boleto (dias)'),
        ),
    ]
