# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0011_auto_20180427_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_internal_subscription',
            field=models.BooleanField(default=False, help_text='Se ativado, organizadores poderão inserir inscrição interna manualmente.', verbose_name='permitir inscrição interna'),
        ),
    ]
