# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0012_auto_20180511_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editorial_body',
            field=models.TextField(blank=True, null=True, verbose_name='corpo editorial'),
        ),
        migrations.AddField(
            model_name='event',
            name='scientific_rules',
            field=models.TextField(blank=True, null=True, verbose_name='normas de evento cientifico'),
        ),
    ]
