# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0013_auto_20180521_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('free', 'gratuito'), ('paid', 'pago'), ('scientific', 'scientific')], default='free', help_text='Como será seu evento?', max_length=15, verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Seu evento terá entrega de Certificados ?', verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_checkin',
            field=models.BooleanField(default=False, help_text='Deseja realizar o checkin com nosso App gratuito?', verbose_name='Checkin'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_extra_activities',
            field=models.BooleanField(default=False, help_text='Seu evento terá: workshops, minicursos?', verbose_name='Atividades extras'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_optionals',
            field=models.BooleanField(default=False, help_text='Você irá vender, opcionais como: hospedagem, alimentação, camisetas?', verbose_name='Opcionais'),
        ),
    ]
