# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0014_auto_20180602_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('free', 'gratuito'), ('paid', 'pago'), ('scientific', 'scientific')], default='free', help_text='Como será seu evento?', max_length=15, verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Seu evento terá entrega de Certificados ?', verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_checkin',
            field=models.BooleanField(default=False, help_text='Deseja realizar o checkin com nosso App gratuito?', verbose_name='Checkin'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_extra_activities',
            field=models.BooleanField(default=False, help_text='Seu evento terá: workshops, minicursos?', verbose_name='Atividades extras'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_optionals',
            field=models.BooleanField(default=False, help_text='Você irá vender, opcionais como: hospedagem, alimentação, camisetas?', verbose_name='Opcionais'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gatheros_event.Category', verbose_name='categoria do evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(verbose_name='data de término do evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(verbose_name='data de início do evento'),
        ),
    ]
