# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0016_auto_20180612_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_survey',
            field=models.BooleanField(default=False, help_text='Seu evento terá formulário com perguntas personalizadas ?', verbose_name='Formulário Personalizado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('free', 'gratuito'), ('paid', 'pago'), ('scientific', 'cientifico')], default='free', help_text='Como será seu evento?', max_length=15, verbose_name='Tipo de evento'),
        ),
    ]
