# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0017_auto_20180613_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='voucher_extra_info',
            field=models.CharField(blank=True, help_text='Informações extras que serão impressas junto com o voucher.', max_length=255, null=True, verbose_name='Informações Extras do Voucher'),
        ),
    ]
