# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0018_info_voucher_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='voucher_extra_info',
            field=models.CharField(blank=True, help_text='Informações extras que serão impressas junto com o voucher.', max_length=2000, null=True, verbose_name='Informações Extras do Voucher'),
        ),
    ]
