# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0021_organization_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_importing',
            field=models.BooleanField(default=False, verbose_name='permitir importação via csv'),
        ),
    ]
