# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0023_event_allow_importing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfFeatureRelease',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_release', serialize=False, to='gatheros_event.Event', verbose_name='evento')),
                ('funcionalidade - form. personalizado', models.BooleanField(default=True, help_text='Liberar funcionalidade de formulário personalizado no evento.')),
                ('funcionalidade - check-in', models.BooleanField(default=True, help_text='Liberar funcionalidade de check-in no evento.')),
                ('funcionalidade - certificado', models.BooleanField(default=True, help_text='Liberar funcionalidade de certificado no evento.')),
                ('funcionalidade - opcionais', models.BooleanField(default=True, help_text='Liberar funcionalidade de opcionais no evento.')),
                ('funcionalidade - atividades extras', models.BooleanField(default=True, help_text='Liberar funcionalidade de atividades extras no evento.')),
            ],
        ),
    ]
