# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0023_event_allow_importing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cnpj_ou_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF ou CNPJ da conta com ou sem pontuações'),
        ),
    ]
