# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0023_event_allow_importing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfiguration',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_configuration', serialize=False, to='gatheros_event.Event', verbose_name='evento')),
                ('feature_survey', models.BooleanField(default=False, help_text='Liberar funcionalidade de formulário personalizado no evento.', verbose_name='funcionalidade - form. personalizado')),
                ('feature_checkin', models.BooleanField(default=False, help_text='Liberar funcionalidade de check-in no evento.', verbose_name='funcionalidade - check-in')),
                ('feature_certificate', models.BooleanField(default=False, help_text='Liberar funcionalidade de certificado no evento.', verbose_name='funcionalidade - certificado')),
                ('feature_products', models.BooleanField(default=False, help_text='Liberar funcionalidade de opcionais no evento.', verbose_name='funcionalidade - opcionais')),
                ('feature_services', models.BooleanField(default=False, help_text='Liberar funcionalidade de atividades extras no evento.', verbose_name='funcionalidade - atividades extras')),
                ('feature_internal_subscription', models.BooleanField(default=False, help_text='Liberar funcionalidade de organizadores poderão inserir inscrição interna manualmente.', verbose_name='funcionalidade - inscrições internas')),
                ('feature_manual_payments', models.BooleanField(default=False, help_text='Liberar funcionalidade de organizadores poderão inserir pagamentos manuais.', verbose_name='funcionalidade - pagamentos manuais')),
            ],
            options={
                'verbose_name': 'Configuração de Features',
                'verbose_name_plural': 'Configurações de Features',
            },
        ),
        migrations.CreateModel(
            name='FeatureManagement',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_management', serialize=False, to='gatheros_event.Event', verbose_name='evento')),
                ('products', models.BooleanField(default=False, help_text='Você irá vender, opcionais como: hospedagem, alimentação, camisetas?', verbose_name='Opcionais')),
                ('services', models.BooleanField(default=False, help_text='Seu evento terá: workshops, minicursos?', verbose_name='Atividades extras')),
                ('checkin', models.BooleanField(default=False, help_text='Deseja realizar o checkin com nosso App gratuito?', verbose_name='Checkin')),
                ('certificate', models.BooleanField(default=False, help_text='Seu evento terá entrega de Certificados ?', verbose_name='Certificado')),
                ('survey', models.BooleanField(default=False, help_text='Seu evento terá formulário com perguntas personalizadas ?', verbose_name='Formulário Personalizado')),
            ],
            options={
                'verbose_name': 'Gestão de Features',
                'verbose_name_plural': 'Gestões de Features',
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='allow_internal_subscription',
        ),
    ]
