# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0023_event_allow_importing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfFeatureRelease',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_release', serialize=False, to='gatheros_event.Event', verbose_name='evento')),
                ('feature_survey', models.BooleanField(default=False, help_text='Liberar funcionalidade de formulário personalizado no evento.', verbose_name='funcionalidade - form. personalizado')),
                ('feature_checkin', models.BooleanField(default=False, help_text='Liberar funcionalidade de check-in no evento.', verbose_name='funcionalidade - check-in')),
                ('feature_certificate', models.BooleanField(default=False, help_text='Liberar funcionalidade de certificado no evento.', verbose_name='funcionalidade - certificado')),
                ('feature_products', models.BooleanField(default=False, help_text='Liberar funcionalidade de opcionais no evento.', verbose_name='funcionalidade - opcionais')),
                ('feature_services', models.BooleanField(default=False, help_text='Liberar funcionalidade de atividades extras no evento.', verbose_name='funcionalidade - atividades extras')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_certificate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_checkin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_extra_activities',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_optionals',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_survey',
        ),
    ]
