# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0024_conffeaturerelease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='has_certificate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_checkin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_extra_activities',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_optionals',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_survey',
        ),
    ]
