# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0025_auto_20180918_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_international',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereco'),
        ),
    ]
