# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0026_auto_20181017_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_international',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='place',
            name='city_international',
            field=models.CharField(blank=True, help_text='Informe a cidade', max_length=255, null=True, verbose_name='Cidade (Fora do Brasil)'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afeganistão'), ('ZA', 'África Do Sul'), ('AL', 'Albânia'), ('DE', 'Alemanha'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antártida'), ('AG', 'Antígua E Barbuda'), ('AN', 'Antilhas Holandesas'), ('SA', 'Arábia Saudita'), ('DZ', 'Argélia'), ('AR', 'Argentina'), ('AM', 'Armênia'), ('AW', 'Aruba'), ('AU', 'Austrália'), ('AT', 'Áustria'), ('AZ  ', 'Azerbaijão'), ('BS', 'Bahamas'), ('BH', 'Bahrein'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Bélgica'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermudas'), ('BO', 'Bolívia'), ('BA', 'Bósnia-Herzegóvina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('BN', 'Brunei'), ('BG', 'Bulgária'), ('BF', 'Burkina Fasso'), ('BI', 'Burundi'), ('BT', 'Butão'), ('CV', 'Cabo Verde'), ('CM', 'Camarões'), ('KH', 'Camboja'), ('CA', 'Canadá'), ('KZ', 'Cazaquistão'), ('TD', 'Chade'), ('CL', 'Chile'), ('CN', 'China'), ('CY', 'Chipre'), ('SG', 'Cingapura'), ('CO', 'Colômbia'), ('CG', 'Congo'), ('KP', 'Coréia Do Norte'), ('KR', 'Coréia Do Sul'), ('CI', 'Costa Do Marfim'), ('CR', 'Costa Rica'), ('HR', 'Croácia (Hrvatska)'), ('CU', 'Cuba'), ('DK', 'Dinamarca'), ('DJ', 'Djibuti'), ('DM', 'Dominica'), ('EG', 'Egito'), ('SV', 'El Salvador'), ('AE', 'Emirados Árabes Unidos'), ('EC', 'Equador'), ('ER', 'Eritréia'), ('SK', 'Eslováquia'), ('SI', 'Eslovênia'), ('ES', 'Espanha'), ('US', 'Estados Unidos'), ('EE', 'Estônia'), ('ET', 'Etiópia'), ('FJ', 'Fiji'), ('PH', 'Filipinas'), ('FI', 'Finlândia'), ('FR', 'França'), ('GA', 'Gabão'), ('GM', 'Gâmbia'), ('GH', 'Gana'), ('GE', 'Geórgia'), ('GI', 'Gibraltar'), ('GB', 'Reino Unido'), ('GD', 'Granada'), ('GR', 'Grécia'), ('GL', 'Groelândia'), ('GP', 'Guadalupe'), ('GU', 'Guam (Território Dos Estados Unidos)'), ('GT', 'Guatemala'), ('G', 'Guernsey'), ('GY', 'Guiana'), ('GF', 'Guiana Francesa'), ('GN', 'Guiné'), ('GQ', 'Guiné Equatorial'), ('GW', 'Guiné-Bissau'), ('HT', 'Haiti'), ('NL', 'Holanda'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungria'), ('YE', 'Iêmen'), ('IM', 'Ilha Do Homem'), ('CX', 'Ilha Natal'), ('PN', 'Ilha Pitcairn'), ('RE', 'Ilha Reunião'), ('AX', 'Ilhas Aland'), ('KY', 'Ilhas Cayman'), ('CC', 'Ilhas Cocos'), ('KM', 'Ilhas Comores'), ('CK', 'Ilhas Cook'), ('FO', 'Ilhas Faroes'), ('FK', 'Ilhas Falkland (Malvinas)'), ('GS', 'Ilhas Geórgia Do Sul E Sandwich Do Sul'), ('MP', 'Ilhas Marianas Do Norte'), ('MH', 'Ilhas Marshall'), ('NF', 'Ilhas Norfolk'), ('SC', 'Ilhas Seychelles'), ('SB', 'Ilhas Solomão'), ('SJ', 'Ilhas Svalbard E Jan Mayen'), ('TK', 'Ilhas Tokelau'), ('TC', 'Ilhas Turks E Caicos'), ('VI', 'Ilhas Virgens (Estados Unidos)'), ('VG', 'Ilhas Virgens (Inglaterra)'), ('WF', 'Ilhas Wallis E Futuna'), ('IN', 'Índia'), ('ID', 'Indonésia'), ('IR', 'Irã'), ('IQ', 'Iraque'), ('IE', 'Irlanda'), ('IS', 'Islândia'), ('IL', 'Israel'), ('IT', 'Itália'), ('JM', 'Jamaica'), ('JP', 'Japão'), ('JE', 'Jersey'), ('JO', 'Jordânia'), ('KE', 'Kênia'), ('KI', 'Kiribati'), ('KW', 'Kuait'), ('LA', 'Laos'), ('LV', 'Látvia'), ('LS', 'Lesoto'), ('LB', 'Líbano'), ('LR', 'Libéria'), ('LY', 'Líbia'), ('LI', 'Liechtenstein'), ('LT', 'Lituânia'), ('LU', 'Luxemburgo'), ('MO', 'Macau'), ('MK', 'Macedônia (República Yugoslava)'), ('MG', 'Madagascar'), ('MY', 'Malásia'), ('MW', 'Malaui'), ('MV', 'Maldivas'), ('ML', 'Mali'), ('MT', 'Malta'), ('MA', 'Marrocos'), ('MQ', 'Martinica'), ('MU', 'Maurício'), ('MR', 'Mauritânia'), ('YT', 'Mayotte'), ('MX', 'México'), ('FM', 'Micronésia'), ('MZ', 'Moçambique'), ('MD', 'Moldova'), ('MC', 'Mônaco'), ('MN', 'Mongólia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MM', 'Myanma'), ('NA', 'Namíbia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NI', 'Nicarágua'), ('NE', 'Níger'), ('NG', 'Nigéria'), ('NU', 'Niue'), ('NO', 'Noruega'), ('NC', 'Nova Caledônia'), ('NZ', 'Nova Zelândia'), ('OM', 'Omã'), ('PW', 'Palau'), ('PA', 'Panamá'), ('PG', 'Papua-Nova Guiné'), ('PK', 'Paquistão'), ('PY', 'Paraguai'), ('PE', 'Peru'), ('PF', 'Polinésia Francesa'), ('PL', 'Polônia'), ('PR', 'Porto Rico'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('KG', 'Quirguistão'), ('CF', 'República Centro-Africana'), ('CD', 'República Democrática Do Congo'), ('DO', 'República Dominicana'), ('CZ', 'República Tcheca'), ('RO', 'Romênia'), ('RW', 'Ruanda'), ('RU', 'Rússia'), ('EH', 'Saara Ocidental'), ('VC', 'Saint Vincente E Granadinas'), ('AS', 'Samoa Americana'), ('WS', 'Samoa Ocidental'), ('SM', 'San Marino'), ('SH', 'Santa Helena'), ('LC', 'Santa Lúcia'), ('BL', 'São Bartolomeu'), ('KN', 'São Cristóvão E Névis'), ('MF', 'São Martim'), ('ST', 'São Tomé E Príncipe'), ('SN', 'Senegal'), ('SL', 'Serra Leoa'), ('RS', 'Sérvia'), ('SY', 'Síria'), ('SO', 'Somália'), ('LK', 'Sri Lanka'), ('PM', 'St. Pierre And Miquelon'), ('SZ', 'Suazilândia'), ('SD', 'Sudão'), ('SE', 'Suécia'), ('CH', 'Suíça'), ('SR', 'Suriname'), ('TJ', 'Tadjiquistão'), ('TH', 'Tailândia'), ('TW', 'Taiwan'), ('TZ', 'Tanzânia'), ('IO', 'Território Britânico Do Oceano Índico'), ('PS', 'Territórios Palestinos Ocupados'), ('TP', 'Timor Leste'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad And Tobago'), ('TN', 'Tunísia'), ('TM', 'Turcomenistão'), ('TR', 'Turquia'), ('TV', 'Tuvalu'), ('UA', 'Ucrânia'), ('UG', 'Uganda'), ('UY', 'Uruguai'), ('UZ', 'Uzbequistão'), ('VU', 'Vanuatu'), ('VA', 'Vaticano'), ('VE', 'Venezuela'), ('VN', 'Vietnã'), ('ZM', 'Zâmbia'), ('ZW', 'Zimbábue')], default='BR', max_length=10, null=True, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='place',
            name='state_international',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code_international',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code_international',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP/Caixa Postal'),
        ),
    ]
