# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0027_auto_20181026_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transfer_tax',
            field=models.BooleanField(default=True, help_text='transferir taxas e despesas financeiras ao participante', verbose_name='transferir taxas'),
        ),
    ]
