# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0028_auto_20190521_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='enable_streaming_page',
            field=models.BooleanField(default=False, verbose_name='Habilitar página de streaming de vídeo'),
        ),
        migrations.AddField(
            model_name='info',
            name='stream_page_button',
            field=models.CharField(blank=True, default='Transmissão ao vivo', max_length=20, verbose_name='Texto do botão da página de vídeo'),
        ),
        migrations.AddField(
            model_name='info',
            name='stream_page_title',
            field=models.CharField(blank=True, default='Transmissão ao vivo', max_length=80, verbose_name='Título da Pàgina de Vídeo'),
        ),
        migrations.AddField(
            model_name='info',
            name='stream_youtube_code',
            field=models.CharField(blank=True, help_text='https://www.youtube.com/watch?v=<strong>CÓDIGO</strong>', max_length=15, null=True, verbose_name='Código do streaming do Youtube'),
        ),
    ]
