# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0030_auto_20190617_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='permalink'),
        ),
    ]
