# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0031_auto_20190809_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hotsite_version',
            field=models.PositiveIntegerField(blank=True, default=2, verbose_name='Versão do hotsite'),
        ),
    ]
