# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 23:17
from __future__ import unicode_literals

from django.db import migrations
import gatheros_event.models.info
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0032_event_hotsite_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image4',
        ),
        migrations.AddField(
            model_name='info',
            name='image_main2',
            field=stdimage.models.StdImageField(blank=True, help_text="Banner com tamanho ideal de 1920px largura x 1006px altura.(png/jpg) e não ultrapasse 10Mb de tamanho - <a target='_blank' href='http://via.placeholder.com/1920x1006'>Exemplo</a>", max_length=255, null=True, upload_to=gatheros_event.models.info.get_image_path, validators=[stdimage.validators.MinSizeValidator(1200, 629), stdimage.validators.MaxSizeValidator(2880, 1509)], verbose_name='imagem principal'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_main',
            field=stdimage.models.StdImageField(blank=True, help_text="Banner do evento, mínimo de: 480px largura x 640px altura.(png/jpg) <a target='_blank' href='http://via.placeholder.com/480x638'>Exemplo </a>", max_length=255, null=True, upload_to=gatheros_event.models.info.get_image_path, validators=[stdimage.validators.MinSizeValidator(480, 638), stdimage.validators.MaxSizeValidator(1400, 1861)], verbose_name='imagem principal'),
        ),
    ]
