# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0035_auto_20200125_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuremanagement',
            name='videos',
            field=models.BooleanField(default=False, help_text='Funcionalidade de vídeos', verbose_name='Videos'),
        ),
    ]
