# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 15:30
from __future__ import unicode_literals

import uuid

from django.db import migrations, models, transaction


def gen_event_uuid(apps, schema_editor):
    Model = apps.get_model('gatheros_event', 'Event')
    while Model.objects.filter(uuid__isnull=True).exists():
        with transaction.atomic():
            for row in Model.objects.filter(uuid__isnull=True)[:1000]:
                row.uuid = uuid.uuid4()
                row.save()

class Migration(migrations.Migration):
    dependencies = [
        ('gatheros_event', '0030_auto_20190617_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(unique=True, editable=False, null=True, ),
        ),
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_event_uuid,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True,
                                   editable=False, null=False, ),
        ),

        migrations.AddField(
            model_name='info',
            name='event2',
            field=models.OneToOneField(null=True,
                                       on_delete=models.deletion.CASCADE,
                                       related_name='info2',
                                       to='gatheros_event.Event',
                                       to_field='uuid', verbose_name='evento'),
        ),

        migrations.AddField(
            model_name='place',
            name='event2',
            field=models.OneToOneField(null=True,
                                       on_delete=models.deletion.CASCADE,
                                       related_name='place2',
                                       to='gatheros_event.Event',
                                       to_field='uuid', verbose_name='evento'),
        ),

        migrations.AddField(
            model_name='featureconfiguration',
            name='event2',
            field=models.OneToOneField(null=True,
                                       on_delete=models.deletion.CASCADE,
                                       related_name='featureconfiguration2',
                                       to='gatheros_event.Event',
                                       to_field='uuid', verbose_name='evento'),
        ),

        migrations.AddField(
            model_name='featuremanagement',
            name='event2',
            field=models.OneToOneField(null=True,
                                       on_delete=models.deletion.CASCADE,
                                       related_name='featuremanagement2',
                                       to='gatheros_event.Event',
                                       to_field='uuid', verbose_name='evento'),
        ),
    ]
