from .mix_boleto import MixBoletoDataCleaner
from .scientific_work import ScientificWorkDataCleaner
from .partner import PartnerDataCleaner
from .service_tags import ServiceTagsDataCleaner
from .importer import ImporterDataCleaner
from .certificate import CertificateDataCleaner
from .associate import AssociateDataCleaner
from .payment import PaymentDataCleaner
from .django_cron import DjangoCronDataCleaner
from .event import EventDataCleaner
from .survey import SurveyDataCleaner
from .subscription import SubscriptionDataCleaner
from .attendance import AttendanceDataCleaner
from .raffel import RaffleDataCleaner
from .addon import AddonDataCleaner
from .person import PersonDataCleaner
from .django_contrib import DjangoContribDataCleaner
