# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 13:32
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.utils.timezone
import gatheros_event.models.mixins.gatheros_model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(blank=True, choices=[('creation', 'Criação'), ('edition', 'Edição'), ('deletion', 'Exclusão')], max_length=10, null=True, verbose_name='tipo de processamento')),
                ('process_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='data e hora de processamento')),
                ('object_type', models.TextField(blank=True, choices=[('gatheros_event.person', 'gatheros_event.person'), ('gatheros_subscription.subscription', 'gatheros_subscription.subscription'), ('payment.transaction', 'payment.transaction'), ('payment.transaction_status', 'payment.transaction_status'), ('attendance.attendance_service', 'attendance.attendance_service'), ('attendance.checkin', 'attendance.checkin'), ('attendance.checkout', 'attendance.checkout')], null=True, verbose_name='Tipo de objeto')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='ID do objeto')),
                ('object_repr', models.TextField(blank=True, null=True, verbose_name='Repr. do objeto')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo a ser sincronizado')),
            ],
            options={
                'verbose_name_plural': 'items de sincronização',
                'verbose_name': 'item de sincronização',
            },
            bases=(gatheros_event.models.mixins.gatheros_model_mixin.GatherosModelMixin, base.models.EntityMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='syncitem',
            unique_together=set([('object_id', 'object_type')]),
        ),
    ]
