###############################################################################
# CUIDADO!
# Esta script é gerenciado pelo CI. Não altere ou mude sem saber o que está
# fazendo.
###############################################################################
# CI-STEP: Destruir e (re)criar container de versão de staging
#
# - o container usa o banco de dados cgsy-postgres criado externamente, que é o
#   mesmo utilizado para o ambiente de desenvolvimento (local).
# - IMPORTANTE manter o nome do container como "cgsy-staging" pois outros
#   scripts utilizam esta referência.
# - env-file "env-cgsy-staging" é construído pelo CI dinamicamente por causa
#   das informações sensíveis.
###############################################################################
version: '2.3'
services:
  cgsy-staging:
    image: cgsy-staging
    container_name: cgsy-staging
    networks:
      - postgres
    ports:
      - "8080:80"
    env_file: ./env-cgsy-staging
  labels:
    - "cgsy_env=staging"

networks:
  postgres:
    external:
      name: env_postgres
