# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0011_auto_20180602_0416'),
        ('gatheros_event', '0015_auto_20180604_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('winner_out', models.BooleanField(help_text='Ganhadores não serão sorteados novamente.', verbose_name='retirar ganhadores')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='gatheros_event.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name_plural': 'sorteios',
                'verbose_name': 'sorteio',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='raffle.Raffle', verbose_name='sorteio')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_winners', to='gatheros_subscription.Subscription', verbose_name='inscrição')),
            ],
            options={
                'verbose_name_plural': 'sorteios',
                'verbose_name': 'sorteio',
            },
        ),
    ]
