from django.core.management.base import BaseCommand

from gatheros_subscription.models import Subscription


class Command(BaseCommand):
    help = 'Importas dados da abac da v2'

    m = {' J.A REZENDE TELESERVIÇOS LTDA': 'REZENDE',
         'ABAEC - ASSOCIAÇÃO BRASILEIRA DE ADVOGADOS DE EMPRESAS DE CONSÓRCIO': 'ABAEC',
         'ABRAHY COMERCIAL IMPORTADORA E EXPORTADORA PARTICIPAÇÕES E SERVIÇOS LTDA': 'ABRAHY',
         'ADEMILAR ADMINISTRADORA DE CONSORCIOS S.A.': 'ADEMILAR',
         'ADM. CONS. BECKER LTDA': 'BECKER',
         'ADM. DE CONS. NAC. LIDER LTDA': 'GRUPO LÍDER',
         'ADMINISTRADORA DE CONSORCIO NACIONAL GAZIN LTDA': 'GAZIN',
         'ADMINISTRADORA DE CONSORCIO NACIONAL HONDA LTDA': 'HONDA',
         'ADMINISTRADORA DE CONSÓRCIO SPENGLER LTDA.': 'SPENGLER',
         'ADMINISTRADORA DE CONSÓRCIO UNICOOB LTDA.': 'UNICOOB',
         'ADV E ASSESSORIA MANEZ E SIMOES PESSOA': 'SIMÔES PESSOA',
         'ALBERTO BRANCO JUNIOR ': 'ALBERTO BRANCO',
         'ANDREASSI CONSULTORIA CONSÓRCIO ': 'ANDREASSI',
         'B3': 'B3',
         'BAMAQ ADMINISTRADORA DE CONSORCIOS LTDA': 'BAMAQ',
         'BANCORBRAS ADM. DE CONS. LTDA\n': 'BANCORBRAS',
         'BANCORBRAS EMPREENDIMENTOS E PARTICIPAÇÕES S.A': 'BANCORBRAS',
         'BANRISUL S.A. - ADMINISTRADORA DE CONSÓRCIOS': 'BANRISUL',
         'BAURU ADMINISTRADORA DE CONSORCIOS LTDA': 'BAURU',
         'BB ADM. DE CONS. S.A.': 'BB',
         'BR CONSORCIOS ADMINISTRADORA DE CONSORCIOS LTDA': 'BR CONSÓRCIOS',
         'BRADESCO ADM. DE CONS. LTDA': 'BRADESCO',
         'BREITKOPF ADMINISTRADORA DE CONSÓRCIO LTDA.': 'BREITKOPF',
         'BRENNER ADM. DE CONS. LTDA': 'BRENNER',
         'CAIXA CONSORCIOS S.A ADM. DE CONSÓRCIOS': 'CAIXA',
         'CAMVEL ADM. DE CONS. LTDA': 'CAMVEL',
         'CANOPUS ADMINISTRADORA DE CONSÓRCIOS S.A. ': 'CANOPUS',
         'CASTRO OLIVEIRA ADVGADOS ': 'CASTRO OLIVEIRA',
         'CHEVYPLAN': 'CHEVYPLAN',
         'CICAL ADM. DE CONS. LTDA': 'CICAL',
         'CIMAVEL ADM. DE CONS. S/C LTDA': 'CIMAVEL',
         'CONCOB - RAFAEL SILVEIRA TOMAZ EPP': 'CONCOB',
         'CONSEG ADMINISTRADORA DE CONSORCIOS S.A ': 'CONSEG',
         'CONSORCIEI PARTICIPAÇÕES S. A.': 'CONSORCIEI',
         'CONSORCIO DEL URUGUAY': 'CONS DEL URUGUAY',
         'DISAL ADM. DE CONS. LTDA': 'DISAL',
         'ELIS REIS TREINAMENTOS, ASSESSORIA EM NEGÓCIOS E ADM DE IMÓVEIS PRÓPRIOS EIRELI-ME': 'ELIS '
                                                                                               'REIS',
         'EMBRACON ADMINISTRADORA DE CONSÓRCIO LTDA': 'EMBRACON',
         'FARROUPILHA ADMINISTRADORA DE CONSÓRCIOS LTDA.': 'FARROUPILHA',
         'FENABRAVE': 'FENABRAVE',
         'FENAUTO': 'FENAUTO',
         'FIPAL ADMINISTRADORA DE CONSÓRCIOS LTDA': 'FIPAL',
         'FRAMAR ASSESSORIA E CORETAGEM DE SEGUROS SS LTDA': 'FRAMAR',
         'FUNCHAL NEGOCIOS E EMPREENDIMENTOS LTDA': 'FUNCHAL',
         'GMAC ADMINISTRADORA DE CONSÓRCIOS LTDA': 'GMAC',
         'GONTIJO MENDES  ADVOGADOS E ASSOCIADOS': 'GONTIJO',
         'GROSCON ADMINISTRADORA DE CONSORCIOS LTDA.': 'GROSCON',
         'HS ADM. DE CONS. LTDA': 'HS',
         'INFOCAR SERVIÇOS DE INFORMAÇÕES LTDA EPP.': 'INFOCAR',
         'ITAU ADM. DE CONS. LTDA': 'ITAU',
         'ITAU ADM. DE CONS. LTDA ': 'ITAU',
         'ITAUNA ADM. DE CONS. LTDA': 'ITAUNA',
         'JCK AMORIM CONSULTORIA EMPRESARIAL LTDA': 'JCK AMORIM ',
         'KNB CORRETORA DE SEGUROS LTDA': 'KNB',
         'LUIZA ADMINISTRADORA DE CONSÓRCIOS LTDA': 'LUIZA',
         'LUIZA ADMINISTRADORA DE CONSÓRCIOS LTDA ': 'LUIZA',
         'MAPFRE SEGUROS GERAIS S.A.': 'MAPFRE',
         'MARTINS E COPETTI ADV ASSOCIADOS': 'MARTINS&COPETTI',
         'MASSEY FERGUSON ADMINISTRADORA DE CONSÓRCIOS LTDA': 'MASSEY FERGUSON',
         'ML GOMES ADVOGADOS ASSOCIADOS': 'ML GOMES',
         'MOTO HONDA DA AMAZÔNIA LTDA ': 'HONDA',
         'MOTOASA ADM. DE CONS. LTDA': 'MOTOASA',
         'MULTIMARCAS ADMINISTRADORA DE CONSORCIOS LTDA.': 'MULTIMARCAS',
         'NANUQUE ADM. DE CONS. LTDA': 'NANUQUE',
         'NEO TECNOLOGIA E CONSULTORIA S/A': 'NEO TECNOLOGIA',
         'NEWCON SOFTWARE S/A': 'NEWCON ',
         'PIMENTEL E ASSOCIADOS ADVOCACIA': 'PIMENTEL',
         'PORTO SEGURO ADM. DE CONS. LTDA': 'PORTO SEGURO',
         'PRIMO ROSSI ADMINISTRADORA DE CONSÓRCIO LTDA.': 'PRIMO ROSSI',
         'RANDON ADMINISTRADORA DE CONSÓRCIOS LTDA.': 'RANDON',
         'REMAZA ADMINISTRADORA DE CONSÓRCIO LTDA': 'REMAZA',
         'RODOBENS ADMINISTRADORA DE CONSÓRCIOS LTDA.': 'RODOBENS',
         'SANTANDER BRASIL ADM. DE CONS. LTDA': 'SANTANDER',
         'SCANIA ADM. DE CONS. LTDA': 'SCANIA',
         'SERVOPA ADMINISTRADORA DE CONSORCIOS LTDA': 'SERVOPA',
         'SICREDI': 'SICREDI',
         'SILVIA VALERIA P. SCAPIN ADV. E CONSUL.': 'VALÉRIA SCAPIN',
         'SIMPALA': 'SIMPALA',
         'SINDICATO DOS CONCESSIONÁRIOS E DISTRIBUIDORES DE VEÍCULOS NO ESTADO DE SÃO PAULO - SINCODIV SP': 'SINCODIV',
         'SINOSSERRA ADM. DE CONS. S/A': 'SINOSSERRA',
         'SOLUCAO ADM. DE CONS. LTDA': 'SOLUÇÃO',
         'SPONCHIADO ADM. DE CONS. LTDA': 'SPONCHIADO ',
         'TARRAF ADM. DE CONS. LTDA': 'TARRAF',
         'UNIFISA ADMINISTRADORA NACIONAL DE CONSORCIOS LTDA': 'UNIFISA',
         'UNIÃO CATARINENSE ADMINISTRADORA DE CONSORCIOS LTDA': 'UNIÃO CAT',
         'VOLVO ADM. DE CONS. LTDA': 'VOLVO',
         'VOLVO ADM. DE CONS. LTDA ': 'VOLVO',
         'WIZ SOLUÇÕES E CORRETAGEM DE SEGUROS S.A': 'FINANSEG'
         }

    def handle(self, *args, **options):
        subs = Subscription.objects.filter(
            event_id=374
        )

        for sub in subs:

            if sub.person.function:
                sub.tag_info = sub.person.function

            if sub.person.institution:
                tag = self.m[sub.person.institution]

                sub.tag_group = tag

                assert len(tag) <= 16, 'len({}), {}'.format(len(tag), tag)

            sub.save()
