# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_event', '0024_auto_20180816_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomServiceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_script', models.TextField(blank=True, help_text='Códigos para serem carregar em páginas diversas.', null=True, verbose_name='Scripts de Rastreamento')),
                ('conversion_script', models.TextField(blank=True, help_text='Códigos para serem carregados após finalizar uma inscrição.', null=True, verbose_name='Scripts de Conversão de Inscrição')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_service_tag', to='gatheros_event.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'Script customizado',
                'verbose_name_plural': 'Scripts customizados',
            },
        ),
    ]
