# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='exhibition_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='código de exibição'),
        ),
    ]
