# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='subscription',
        ),
        migrations.AlterUniqueTogether(
            name='defaultfieldoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='defaultfieldoption',
            name='field',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='field',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='field',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='fieldoption',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fieldoption',
            name='field',
        ),
        migrations.RemoveField(
            model_name='form',
            name='event',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='DefaultField',
        ),
        migrations.DeleteModel(
            name='DefaultFieldOption',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='FieldOption',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
