# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0002_lot_exhibition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='preço'),
        ),
    ]
