# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0002_auto_20180119_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='function',
            field=models.CharField(choices=[('function-hide', 'Ocultar'), ('function-show', 'Mostrar'), ('function-required', 'Mostrar e Tornar obrigatório')], default='function-hide', help_text='Cargo ou função que exerce profissialmente.', max_length=25, verbose_name='Cargo/Função'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='institution',
            field=models.CharField(choices=[('institution-hide', 'Ocultar'), ('institution-show', 'Mostrar'), ('institution-required', 'Mostrar e Tornar obrigatório')], default='institution-hide', help_text='Empresa, Igreja, Fundação, etc.', max_length=25, verbose_name='Empresa/Instituição'),
        ),
    ]
