# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gatheros_subscription', '0003_auto_20180209_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='institution_cnpj',
            field=models.CharField(
                choices=[
                    ('institution-cnpj-hide', 'Ocultar'),
                    ('institution-cnpj-show', 'Mostrar'), (
                        'institution-cnpj-required',
                        'Mostrar e Tornar obrigatório')],
                default='institution-cnpj-hide',
                help_text='CNPJ da empresa com a qual você o(a) partcipante'
                          ' vinculado(a).',
                max_length=35, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='address',
            field=models.CharField(
                choices=[('address-hide', 'Ocultar'),
                         ('address-show', 'Mostrar')],
                default='address-hide',
                help_text='Configuração do campo "Endereço" no formulário.'
                          ' Isto exigirá que alguns campos sejam'
                          ' obrigatórios.',
                max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='birth_date',
            field=models.CharField(
                choices=[('birth-date-hide', 'Ocultar'),
                         ('birth-date-show', 'Mostrar'), (
                             'birth-date-required',
                             'Mostrar e Tornar obrigatório')],
                default='birth-date-hide',
                help_text='Configuração do campo "Data de Nascimento" no'
                          ' formulário.',
                max_length=35,
                verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='cpf',
            field=models.CharField(
                choices=[('cpf-hide', 'Ocultar'), ('cpf-show', 'Mostrar'),
                         ('cpf-required', 'Mostrar e Tornar obrigatório')],
                default='cpf-hide',
                help_text='Configuração do campo "CPF" no formulário.',
                max_length=35, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='function',
            field=models.CharField(
                choices=[('function-hide', 'Ocultar'),
                         ('function-show', 'Mostrar'), (
                             'function-required',
                             'Mostrar e Tornar obrigatório')],
                default='function-hide',
                help_text='Cargo ou função que exerce profissialmente.',
                max_length=35, verbose_name='Cargo/Função'
            ),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='institution',
            field=models.CharField(
                choices=[('institution-hide', 'Ocultar'),
                         ('institution-show', 'Mostrar'), (
                             'institution-required',
                             'Mostrar e Tornar obrigatório')],
                default='institution-hide',
                help_text='Empresa, Igreja, Fundação, etc.',
                max_length=35,
                verbose_name='Empresa/Instituição'),
        ),
    ]
