# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0003_auto_20180209_1603'),
        ('gatheros_subscription', '0003_auto_20180209_1552'),
    ]

    operations = [
    ]
