# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0004_auto_20180219_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='allow_installments',
            field=models.BooleanField(default=False, help_text='Permitir parcelamento do valor do ingresso.', verbose_name='parcelamento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='free_installments',
            field=models.CharField(blank=True, choices=[('INSTALLMENT_2', '2'), ('INSTALLMENT_3', '3'), ('INSTALLMENT_4', '4'), ('INSTALLMENT_5', '5'), ('INSTALLMENT_6', '6'), ('INSTALLMENT_7', '7'), ('INSTALLMENT_8', '8'), ('INSTALLMENT_9', '9')], help_text='Número de parcelas que irá assumir juros de parcelamento do participante.', max_length=15, null=True, verbose_name='parcelas isentas de juros'),
        ),
        migrations.AddField(
            model_name='lot',
            name='transfer_interest_rate',
            field=models.BooleanField(default=False, help_text='Repasse os juros das parcelas para o participante e receba o valor integral da parcela.', verbose_name='repassar juros ao participante'),
        ),
    ]
