# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0004_auto_20180219_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('canceled', 'Cancelado'), ('awaiting', 'Pendente')], default='awaiting', max_length=15, verbose_name='status'),
        ),
    ]
