# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0004_auto_20180219_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='instalments',
            field=models.BooleanField(default=False, help_text='Permitir parcelamento do valor do ingresso.', verbose_name='parcelamento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='transfer_interest_rate',
            field=models.BooleanField(default=False, help_text='Repasse os juros das parcelas para o participante e receba o valor integral da parcela.', verbose_name='repassar juros de parcelamento ao participante'),
        ),
    ]
