# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0005_auto_20180220_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='instalments',
            new_name='installments',
        ),
    ]
