# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0006_auto_20180220_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='allow_installments',
            field=models.BooleanField(default=False, help_text='Permitir parcelamento do valor do ingresso.', verbose_name='parcelamento'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='installments',
            field=models.CharField(blank=True, choices=[('2', 'INSTALLMENT_2'), ('3', 'INSTALLMENT_3'), ('4', 'INSTALLMENT_4'), ('5', 'INSTALLMENT_5'), ('6', 'INSTALLMENT_6'), ('7', 'INSTALLMENT_7'), ('8', 'INSTALLMENT_8'), ('9', 'INSTALLMENT_9')], max_length=15, null=True, verbose_name='parcelas'),
        ),
    ]
