# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0006_auto_20180223_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='free_installments',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='transfer_interest_rate',
        ),
        migrations.AddField(
            model_name='lot',
            name='allow_installment',
            field=models.BooleanField(default=True, verbose_name='permitir parcelamento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='installment_limit',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Número de parcelas permitido.', verbose_name='parcelas'),
        ),
        migrations.AddField(
            model_name='lot',
            name='num_install_interest_absortion',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de parcelas que deseja absorver os juros.', null=True, verbose_name='absorver juros de parcelas'),
        ),
    ]
