# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0009_eventsurvey'),
        ('survey', '0001_initial'),
        ('gatheros_subscription', '0007_auto_20180301_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lots', to='gatheros_event.EventSurvey', verbose_name='formulario'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to='survey.Author', verbose_name='autor de resposta'),
        ),
    ]
