# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0007_auto_20180228_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='free_installments',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='transfer_interest_rate',
        ),
    ]
