# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0009_auto_20180329_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='rsvp_restrict',
            field=models.BooleanField(default=False, help_text='Somente associados podem se inscrever neste lote.', verbose_name='restrito a associados'),
        ),
    ]
