# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0009_auto_20180329_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notified',
            field=models.BooleanField(default=False, editable=False, help_text='Participante notificado.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='synchronized',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
