# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0011_auto_20180602_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='cpf',
            field=models.CharField(choices=[('cpf-hide', 'Ocultar'), ('cpf-show', 'Mostrar'), ('cpf-required', 'Mostrar e Tornar obrigatório')], default='cpf-hide', help_text='Configuração do campo de documentos pessoais no formulário.', max_length=35, verbose_name='CPF ou ID/Passport'),
        ),
    ]
