# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0012_auto_20180612_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='test_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
