# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0014_subscription_event_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_chosen_free_lot',
            field=models.BooleanField(default=False, verbose_name='esse lote foi selecionado após perder multi-lotes'),
        ),
    ]
