# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0014_subscription_event_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='attended_on',
        ),
    ]
