# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('gatheros_subscription', '0014_subscription_event_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='survey.Author', verbose_name='autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.AddField(
            model_name='subscriptionauthor',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_author', to='gatheros_subscription.Subscription', verbose_name='inscrição'),
        ),
    ]
