# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0016_auto_20180924_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='obs',
            field=models.TextField(blank=True, help_text='Observações Gerais', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tag_group',
            field=models.CharField(blank=True, help_text='Informação de grupo do participante', max_length=16, null=True, verbose_name='informação de grupo'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tag_info',
            field=models.CharField(blank=True, help_text='Informação customizada para sair no crachá do participante', max_length=16, null=True, verbose_name='informação para crachá'),
        ),
    ]
