# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0017_auto_20190325_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='accredited',
            field=models.BooleanField(default=False, help_text='Pessoa já foi atendimento pelo serviço de credenciamento.', verbose_name='credenciado'),
        ),
    ]
