# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0018_subscription_accredited'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='accredited_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='credenciado em'),
        ),
    ]
