# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0019_subscription_accredited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='accredited',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='accredited_on',
        ),
    ]
