# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0020_auto_20190401_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='completed',
            field=models.BooleanField(default=False, help_text='Inscrições que passaram por todo o fluxo de inscrições.', verbose_name='completa'),
        ),
    ]
