# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0021_auto_20190513_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='gatheros_subscription.LotCategory', verbose_name='categoria'),
        ),
    ]
