# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0022_auto_20190710_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.CharField(blank=True, help_text='Informações adicionais sobre o lote (60 caracteres).', max_length=60, null=True, verbose_name='descrição rápida'),
        ),
        migrations.AddField(
            model_name='lot',
            name='hide_dates',
            field=models.BooleanField(default=False, help_text='Ocultar data inicial e final do lote.', verbose_name='ocultar datas do lote'),
        ),
    ]
