# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buzzlead', '0001_initial'),
        ('gatheros_subscription', '0023_auto_20190823_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='buzzlead_campaign',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='buzzlead.BuzzLeadCampaign', verbose_name='campanha buzzlead'),
        ),
    ]
