version: '2.3'
services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    networks:
      - postgres
    volumes:
      - /tmp/bkp:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cgsyplatform
      - POSTGRES_USER=congressy
      - POSTGRES_PASSWORD=congressy

networks:
  postgres:
