# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mix_boleto', '0002_auto_20181009_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixboleto',
            name='mix_subscription_id',
            field=models.SmallIntegerField(db_index=True, verbose_name='ID de Inscrição (MixEvents)'),
            preserve_default=False,
        ),
    ]
