# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('gatheros_event', '0008_auto_20180306_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(
                    default='Certificamos que {{NOME}} participou do evento {{EVENTO}} no dia 1 de abril de 2018, com carga horário de 4 horas.',
                    help_text='Texto principal do certificado.',
                    verbose_name='texto')),
                ('text_font_size',
                 models.PositiveIntegerField(blank=True, default=20,
                                             help_text='Tamanho da fonte em (px)',
                                             null=True,
                                             verbose_name='tamaho da fonte do texto')),
                ('text_width',
                 models.PositiveIntegerField(blank=True, default=634,
                                             help_text='tamanho (px) da largura do bloco.',
                                             null=True,
                                             verbose_name='largura do bloco do texto')),
                ('text_height',
                 models.PositiveIntegerField(blank=True, default=348,
                                             help_text='tamanho (px) da altura do bloco.',
                                             null=True,
                                             verbose_name='altura do bloco do texto')),
                ('text_line_height', models.FloatField(blank=True,
                                                       help_text='espaço entre-linhas (cm) do conteúdo.',
                                                       max_length=3, null=True,
                                                       verbose_name='espaço entre-linhas do texto')),
                ('text_position_x', models.FloatField(blank=True, default=191,
                                                      help_text='distância do bloco no eixo X.',
                                                      null=True,
                                                      verbose_name='posição X do texto')),
                ('text_position_y', models.FloatField(blank=True, default=309,
                                                      help_text='distância do bloco no eixo Y.',
                                                      max_length=5, null=True,
                                                      verbose_name='posição Y do texto')),
                ('title_content',
                 models.CharField(blank=True, default='Certificado',
                                  max_length=50, null=True,
                                  verbose_name='título')),
                ('title_font_size',
                 models.PositiveIntegerField(blank=True, default=60,
                                             help_text='Tamanho da fonte em (px)',
                                             null=True,
                                             verbose_name='tamaho da fonte do título')),
                ('title_position_x', models.FloatField(blank=True, default=286,
                                                       help_text='distância do bloco no eixo X.',
                                                       null=True,
                                                       verbose_name='posição X do título')),
                ('title_position_y', models.FloatField(blank=True, default=192,
                                                       help_text='distância do bloco no eixo Y.',
                                                       max_length=5, null=True,
                                                       verbose_name='posição Y do título')),
                ('title_hide', models.BooleanField(default=False,
                                                   verbose_name='esconder título')),
                ('date_font_size',
                 models.PositiveIntegerField(blank=True, default=20,
                                             help_text='Tamanho da fonte em (px)',
                                             null=True,
                                             verbose_name='tamaho da fonte da data')),
                ('date_position_x', models.FloatField(blank=True, default=15,
                                                      help_text='distância do bloco no eixo X.',
                                                      max_length=5, null=True,
                                                      verbose_name='posição X da data')),
                ('date_position_y', models.FloatField(blank=True, default=463,
                                                      help_text='distância do bloco no eixo Y.',
                                                      max_length=5, null=True,
                                                      verbose_name='posição Y da data')),
                ('date_hide', models.BooleanField(default=False,
                                                  verbose_name='esconder data')),
                ('event', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificate', to='gatheros_event.Event',
                    verbose_name='evento')),
            ],
            options={
                'verbose_name_plural': 'certificados',
                'verbose_name': 'certificado',
            },
        ),
    ]
