# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:07
from __future__ import unicode_literals

import certificate.models
from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='background_image',
            field=stdimage.models.StdImageField(blank=True, help_text="Imagem de fundo do certificado, mínimo de: 595px largura x 842 altura.(png/jpg) <a  target='_blank'href='http://via.placeholder.com/595x842'>Exemplo</a>", null=True, upload_to=certificate.models.get_image_path, validators=[stdimage.validators.MinSizeValidator(595, 842)], verbose_name='imagem de fundo do certificado do evento'),
        ),
    ]
