# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 14:09
from __future__ import unicode_literals

import certificate.models
from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='date_content',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='background_image',
            field=stdimage.models.StdImageField(blank=True, help_text="Imagem de fundo do certificado, mínimo de: 1402px largura x 991px altura.(png/jpg) <a  target='_blank'href='http://via.placeholder.com/1402x991'>Exemplo</a>", null=True, upload_to=certificate.models.get_image_path, validators=[stdimage.validators.MinSizeValidator(1402, 991)], verbose_name='imagem de fundo do certificado do evento'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_font_size',
            field=models.FloatField(blank=True, default=20, help_text='Tamanho da fonte em (px)', null=True, verbose_name='tamaho da fonte da data'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_position_x',
            field=models.FloatField(blank=True, default=15, help_text='distância do bloco no eixo X.', null=True, verbose_name='posição X da data'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_position_y',
            field=models.FloatField(blank=True, default=463, help_text='distância do bloco no eixo Y.', null=True, verbose_name='posição Y da data'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text_font_size',
            field=models.FloatField(blank=True, default=20, help_text='Tamanho da fonte em (px)', null=True, verbose_name='tamaho da fonte do texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text_height',
            field=models.FloatField(blank=True, default=348, help_text='tamanho (px) da altura do bloco.', null=True, verbose_name='altura do bloco do texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text_line_height',
            field=models.FloatField(blank=True, default=22, help_text='espaço entre-linhas (cm) do conteúdo.', null=True, verbose_name='espaço entre-linhas do texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text_position_y',
            field=models.FloatField(blank=True, default=309, help_text='distância do bloco no eixo Y.', null=True, verbose_name='posição Y do texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text_width',
            field=models.FloatField(blank=True, default=634, help_text='tamanho (px) da largura do bloco.', null=True, verbose_name='largura do bloco do texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_font_size',
            field=models.FloatField(blank=True, default=60, help_text='Tamanho da fonte em (px)', null=True, verbose_name='tamaho da fonte do título'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_position_y',
            field=models.FloatField(blank=True, default=192, help_text='distância do bloco no eixo Y.', null=True, verbose_name='posição Y do título'),
        ),
    ]
