# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20180611_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='event_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='local do evento'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='text_center',
            field=models.BooleanField(default=False, verbose_name='centralizar texto'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title_position_y',
            field=models.FloatField(blank=True, default=192, help_text='distância do bloco no eixo Y.', max_length=5, null=True, verbose_name='posição Y do título'),
        ),
    ]
