# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_auto_20180612_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='only_attending_participantes',
            field=models.BooleanField(default=True, verbose_name='apenas para presentes(check-in)'),
        ),
    ]
