# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20180615_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='font_color',
            field=models.CharField(blank=True, default='#565656', max_length=20, null=True, verbose_name='cor da fonte'),
        ),
    ]
