# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bittle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.URLField(max_length=1024)),
                ('hash', models.CharField(max_length=10)),
                ('short_url', models.URLField()),
                ('_clicks', models.PositiveIntegerField(blank=True, db_column='click', editable=False)),
                ('_referrers', jsonfield.fields.JSONField(blank=True, editable=False)),
                ('check_stamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
