# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 16:46
from __future__ import unicode_literals

import base.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_event', '0031_auto_20190809_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzLeadCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=6, verbose_name='ID da campanha')),
                ('campaign_owner_token', models.CharField(max_length=110, verbose_name='API Token do assinante')),
                ('signature_price', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='Valor da assinatura de uso dos serviços da Buzzlead', max_digits=25, verbose_name='valor da assinatura')),
                ('signature_email', models.CharField(max_length=110, verbose_name='E-mail do assinante')),
                ('congressy_percent', models.DecimalField(decimal_places=10, help_text='Valor percentual da congressy pago pela integração.', max_digits=25, max_length=5, verbose_name='percentual congressy')),
                ('terms', models.TextField(blank=True, help_text='Regulamento do evento de indicação, feito pelo organizador. A BuzzLead em si possui outros critérios de uso.', null=True, verbose_name='regulamento de indicação')),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzlead_campaigns', to='gatheros_event.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name_plural': 'campanhas buzzlead',
                'ordering': ('event__name', 'event__date_start', 'pk'),
                'verbose_name': 'campanha buzzlead',
            },
            bases=(models.Model, base.models.EntityMixin),
        ),
    ]
