version: "2"
services:
  redis:
    image: redis:4-alpine
    networks:
      - redis
    volumes:
      - "redis:/data"

  cgsy:
    image: 871800672816.dkr.ecr.us-east-1.amazonaws.com/cgsy:latest
    networks:
      - redis
    volumes:
      - "cgsy_media:/var/www/cgsy/media_dev"
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - DOMAIN=ev.congressy.com
      - FORCE_HTTPS=true
      - AWS_KEY=<aws_key>
      - AWS_SECRET=<aws_secret>
      - BUCKET_LOCATION=us-east-1
      - BUCKET_NAME=cgsyplatform
      - CRON_SYNC_MINUTES_OUT=8
      - CRON_SYNC_MINUTES_IN=5
      - DBHOST=congressy.cy6gssymlczu.us-east-1.rds.amazonaws.com
      - DBUSER=congressy
      - DBPASS=4UnADjyMjeeB7GSc
      - DBNAME=cgsyplatform
      - DBPORT=5499
    labels:
      - io.rancher.service.external_lb.endpoint=lb-cgsy

networks:
  redis:

volumes:
  cgsy_media:
  redis:
