# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180802_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='human_display',
            field=models.TextField(blank=True, null=True, verbose_name='nome exibido a humanos'),
        ),
    ]
