# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 17:28
from __future__ import unicode_literals

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_event', '0013_auto_20180521_1728'),
        ('gatheros_subscription', '0009_auto_20180329_1611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='área temática')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_categories', to='gatheros_event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_authors', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
            bases=(base.models.EntityMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('artigo', 'Artigo'), ('banner', 'Banner'), ('resumo', 'Resumo')], default='artigo', max_length=25, verbose_name='modalidades')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('summary', models.TextField(verbose_name='resumo')),
                ('keywords', models.CharField(help_text='Separados por vírgula', max_length=255, verbose_name='palavras chaves')),
                ('article_file', models.FileField(blank=True, null=True, upload_to='scientific_work/artigos/')),
                ('banner_file', models.FileField(blank=True, null=True, upload_to='scientific_work/banners/')),
                ('accepts_terms', models.BooleanField(verbose_name='termos de trabalhos científicos')),
                ('published', models.BooleanField(default=False, verbose_name='publicado')),
                ('area_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='works', to='scientific_work.AreaCategory')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='gatheros_subscription.Subscription', verbose_name='trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='WorkConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='data inicial')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='data final')),
                ('presenting_type', models.CharField(choices=[('oral', 'Oral'), ('poster', 'Poster'), ('oral e poster', 'Oral e Poster')], default='oral', max_length=25, verbose_name='tipos de apresentações')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_config', to='gatheros_event.Event')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='scientific_work.Work', verbose_name='autor'),
        ),
    ]
