# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:39
from __future__ import unicode_literals

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_subscription', '0010_auto_20180514_1441'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_authors', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
            bases=(base.models.Entity, models.Model),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('artigo', 'Artigo'), ('banner', 'Banner'), ('resumo', 'Resumo')], default='artigo', max_length=25, verbose_name='modalidades')),
                ('area_category', models.CharField(choices=[('ensino', 'Ensino'), ('gestao', 'Gestão'), ('marketing', 'Marketing'), ('pesquisa', 'Pesquisa')], default='ensino', max_length=25, verbose_name='área temática')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='resumo')),
                ('keywords', models.CharField(help_text='Separados por vírgula', max_length=255, verbose_name='palavras chaves')),
                ('article_file', models.FileField(blank=True, null=True, upload_to='scientific_work/artigos/')),
                ('banner_file', models.FileField(blank=True, null=True, upload_to='scientific_work/banners/')),
                ('accepts_terms', models.BooleanField(verbose_name='termos de trabalhos científicos')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='gatheros_subscription.Subscription', verbose_name='trabalho')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='scientific_work.Work', verbose_name='autor'),
        ),
    ]
