# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0013_auto_20180518_1107'),
        ('scientific_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='data inicial')),
                ('date_end', models.DateTimeField(verbose_name='data final')),
                ('allow_submissions', models.BooleanField(default=False, verbose_name='permitir submissões')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_configs', to='gatheros_event.Event')),
            ],
        ),
    ]
