# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workconfig',
            name='allow_unconfirmed_subscriptions',
            field=models.BooleanField(default=False, verbose_name='permitir inscrições não confirmadas'),
        ),
        migrations.AlterField(
            model_name='work',
            name='area_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='scientific_work.AreaCategory', verbose_name='areas tematicas'),
        ),
        migrations.AlterField(
            model_name='workconfig',
            name='presenting_type',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('poster', 'Poster'), ('oral e poster', 'Oral e Poster')], default='oral', max_length=25, null=True, verbose_name='tipos de apresentações'),
        ),
    ]
