# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='accepts_terms',
            field=models.BooleanField(verbose_name='termos de trabalhos científicos'),
        ),
        migrations.AlterField(
            model_name='work',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
