# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_event', '0013_auto_20180518_1107'),
        ('scientific_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='área temática')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_categories', to='gatheros_event.Event')),
            ],
        ),
    ]
