# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='summary',
            field=models.TextField(default='resumão da porra', verbose_name='resumo'),
            preserve_default=False,
        ),
    ]
