# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0002_submissionconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionConfig',
            new_name='WorkConfig',
        ),
    ]
