# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0002_areacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='area_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='works', to='scientific_work.AreaCategory'),
        ),
    ]
