# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0003_auto_20180724_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='modality',
            field=models.CharField(choices=[('artigo', 'Resumo - Abstract'), ('banner', 'Poster')], default='artigo', max_length=25, verbose_name='modalidades'),
        ),
    ]
