# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0003_auto_20180518_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workconfig',
            name='allow_submissions',
        ),
        migrations.AddField(
            model_name='workconfig',
            name='presenting_type',
            field=models.CharField(choices=[('oral', 'Oral'), ('poster', 'Poster'), ('oral e poster', 'Oral e Poster')], default='oral', max_length=25, verbose_name='tipos de apresentações'),
        ),
    ]
