# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_work', '0004_auto_20180518_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workconfig',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='workconfig',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data inicial'),
        ),
        migrations.AlterField(
            model_name='workconfig',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_config', to='gatheros_event.Event'),
        ),
    ]
