# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceservice',
            name='printer_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. impressora'),
        ),
        migrations.AddField(
            model_name='attendanceservice',
            name='printing_queue_webhook',
            field=models.TextField(blank=True, help_text='Use o endereço completo incluindo http(s)://', null=True, verbose_name='Webhook de fila de impressão'),
        ),
        migrations.AddField(
            model_name='attendanceservice',
            name='pwa_pin',
            field=models.CharField(blank=True, help_text='Acesso ao aplicativo PWA', max_length=12, null=True, verbose_name='PIN de acesso'),
        ),
    ]
