# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190321_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceservice',
            name='printer_number',
        ),
    ]
