# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190321_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tempo informado pelo organizador'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tempo informado pelo organizador'),
        ),
    ]
