# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendanceservice_printer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceservice',
            name='accreditation',
            field=models.BooleanField(default=False, help_text='Este é o serviço de credenciamento? O evento só poderá ter um.', verbose_name='Credenciamento principal'),
        ),
        migrations.AddField(
            model_name='attendanceservice',
            name='printer_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. impressora'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tempo informado pelo organizador'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='registration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tempo informado pelo organizador'),
        ),
    ]
