# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 18:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='liquid_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Qual o valor liquido que você espera receber pela venda deste item opcional?', max_digits=10, verbose_name='preço líquido'),
        ),
        migrations.AddField(
            model_name='service',
            name='liquid_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Qual o valor liquido que você espera receber pela venda deste item opcional?', max_digits=10, verbose_name='preço líquido'),
        ),
    ]
