# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatheros_subscription', '0011_auto_20180602_0416'),
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionproduct',
            unique_together=set([('subscription', 'optional')]),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionservice',
            unique_together=set([('subscription', 'optional')]),
        ),
    ]
