# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 18:04
from __future__ import unicode_literals

import addon.models.optional
from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0002_auto_20180604_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=stdimage.models.StdImageField(blank=True, help_text='Imagem de apresentação (tamanho mínimo: 900px x 580px).', null=True, upload_to=addon.models.optional.get_image_path, validators=[stdimage.validators.MaxSizeValidator(2700, 1740)], verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='service',
            name='banner',
            field=stdimage.models.StdImageField(blank=True, help_text='Imagem de apresentação (tamanho mínimo: 900px x 580px).', null=True, upload_to=addon.models.optional.get_image_path, validators=[stdimage.validators.MaxSizeValidator(2700, 1740)], verbose_name='imagem'),
        ),
    ]
