# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_auto_20180817_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, help_text='Inscrições que são feitas em opcional que possui identificador único não podem fazer inscrição em outro opcional com o mesmo identificador.', max_length=24, null=True, verbose_name='Identificador único'),
        ),
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.CharField(blank=True, help_text='Inscrições que são feitas em atividade extra que possui identificador único não podem fazer inscrição em outra atividadade extra com o mesmo identificador.', max_length=24, null=True, verbose_name='Identificador único'),
        ),
    ]
