# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatheros_event', '0007_auto_20180219_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner', serialize=False, to='gatheros_event.Person')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('non_active', 'Não-ativo'), ('suspended', 'Suspenso')], default='non_active', max_length=30, verbose_name='status')),
                ('approved', models.BooleanField(default=False, verbose_name='aprovado')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='PartnerContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='gatheros_event.Event')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='partner.Partner')),
            ],
            options={
                'verbose_name': 'Contrato de Parceiro',
                'verbose_name_plural': 'Contratos de Parceiros',
            },
        ),
        migrations.CreateModel(
            name='PartnerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='porcentagem')),
            ],
            options={
                'verbose_name': 'Plano de Parceiro',
                'verbose_name_plural': 'Planos de Parceiros',
            },
        ),
        migrations.AddField(
            model_name='partnercontract',
            name='partner_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='partner.PartnerPlan'),
        ),
    ]
